### ISSUE TITLE
Regression: show diff flag no longer working after 1.0.0

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1000]
### Problem

After 1.0.0, `--show-diff` no longer works and fails to let you continue on because of log.

**Comment by sideninja** [comment]
@chasefleming I can't reproduce the issue, here's trying to deploy a project:

```
./main project deploy --show-diff --update

Deploying 2 contracts for accounts: emulator-account

Bar -> 0xf8d6e0586b0a20c7 [skipping, no changes found]
import Bar from 0xf8d6e0586b0a20c7
import Zoo from 0xf8d6e0586b0a20c7

pub contract Foo {
	pub var X: String

	pub init() {
		self.X = "MOO"
	}

	pub fun bye() {
		Bar.bye()
	}
}

? Do you wish to deploy this contract?? [y/N] █
```

**Comment by sideninja** [comment]
If you mean it doesn't work when adding to add contract then that's not a regression since that feature doesn't exist yet.

**Comment by chasefleming** [comment]
<img width="687" alt="Screenshot 2023-04-26 at 9 50 48 AM" src="https://user-images.githubusercontent.com/1666730/234647164-4bf7ed18-644e-48a3-a264-c74e52366d5f.png">

@sideninja definitely happening for me on master. When you try to input an answer with the logger running there it is erased and you can't continue.
