### ISSUE TITLE
v1.0.0 cuts of error message before panic

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1002]
### Instructions

When upgrading overflow to v1.0.0 of flowkit and testing this change in the .find codebase we discovered the following error that used to just work fine https://github.com/findonflow/find/pull/373

### Problem

The error message is truncated and does not show the acual panic error
### Steps to Reproduce

Panic with a message in a deeply nested call hirarchy. Or look at the find test as an example

### Acceptance Criteria

Error messages need to include the panic message, if we have to cut it we atleast have to add the latest frame. 

The first and last frame is really what is most important
### Context

Overflow upgraded to v1.0.0 flowkit

**Comment by sideninja** [comment]
This is really weird. What is used to send a transaction? flowkit? I don't understand why would that be cut, will look into it tho, thanks for reporting.

**Comment by sideninja** [comment]
@bjartek I tried reproducing the issue using the CLI which just uses sendTransaction from flowkit and I can see the whole stack:

```
Transaction ID: f0e0ccbd6fe509a88cb000c7eacc6cf3ad898dce3bfbee1445b1059bb6b30ab6

❌ Transaction Error
execution error code 1101: [Error Code: 1101] error caused by: 1 error occurred:
	* transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
 --> f0e0ccbd6fe509a88cb000c7eacc6cf3ad898dce3bfbee1445b1059bb6b30ab6:5:2
  |
5 | 		Stack.xoo()
  | 		^^^^^^^^^^^

  --> f8d6e0586b0a20c7.Stack:29:2
   |
29 | 		self.goo()	
   | 		^^^^^^^^^^

  --> f8d6e0586b0a20c7.Stack:25:2
   |
25 | 		self.moo()
   | 		^^^^^^^^^^

  --> f8d6e0586b0a20c7.Stack:21:2
   |
21 | 		self.zoo()
   | 		^^^^^^^^^^

  --> f8d6e0586b0a20c7.Stack:17:2
   |
17 | 		self.bar()
   | 		^^^^^^^^^^

  --> f8d6e0586b0a20c7.Stack:13:2
   |
13 | 		self.foo()
   | 		^^^^^^^^^^

error: panic: X
 --> f8d6e0586b0a20c7.Stack:9:2
  |
9 | 		panic(self.X)
  | 		^^^^^^^^^^^^^

```

Do you have any ideas what else should I try to reproduce? Is it possible is something related to overflow?

**Comment by sideninja** [comment]
The poop emoji isn't our work haha

**Comment by bjartek** [comment]
I know, the 💩 is in overflow. :) Gotta have those emoji!

**Comment by sideninja** [comment]
@bjartek do you have any suggestions about the reproduction of this? like I said I tried using CLI and it showed the stack.

**Comment by bjartek** [comment]
How many characters is your stack? The one we had where almost 2k character when it was cut of.

**Comment by sideninja** [comment]
That's a good idea yeah. Will try to make the stack bigger in size not depth.

**Comment by bluesign** [comment]
it's in cadence, I will figure out exact place very soon

**Comment by bjartek** [comment]
was this fixed?

**Comment by bluesign** [comment]
> was this fixed?

it is on Cadence v0.39.0 , I think when emulator updated to v0.39.1 it will be included. I can make a PR today.
