### ISSUE TITLE
v1.0.1 flowkit not tagged

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1003]
### Instructions

The new v1.0.1 of cli did not tag flowkit even though it changed code in flowkit

### Problem

I need to pin to commit not to version in overflow, i dont like that

### Steps to Reproduce

None
### Acceptance Criteria

Whenever there is a tag that touches flowkit code it is tagged along with flow-cli, or it is always tagged. Maybe that is easier

### Context

Migrate overflow to v1 of flowkit

**Comment by sideninja** [comment]
@bjartek will tag the flowkit today, just have some homebrew issues I need to sort out.

**Comment by sideninja** [comment]
Tagged
