### ISSUE TITLE
Unable to install on Ubuntu

### ISSUE THREAD

**Issue by crash13override** [onflow/flow-cli#1036]
When I try to run the install script I get the following error
sh: 15: Syntax error: "(" unexpected

That seems to be related to this line in particular
https://github.com/onflow/flow-cli/blob/fa42f688b6f017f5b24a77614e7029178c07ac4d/install.sh#L15

added on a recent commit
https://github.com/onflow/flow-cli/commit/ba04a016670389cf9748efde29e62121598c7590#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44f

On a separate note, the links to the install guide on the readme are now pointing to a 404 and should be updated to the correct URL

https://docs.onflow.org/flow-cli/install is now https://developers.flow.com/tooling/flow-cli/install (different domain and under tooling folder)

Thanks!
Luca

**Comment by sideninja** [comment]
cc @jribbink can you look into this and fix accordingly? Thanks

**Comment by jribbink** [comment]
> cc @jribbink can you look into this and fix accordingly? Thanks

Yeah, looks like the script I wrote works for bash, but not dash and since /bin/sh points to dash in newer debian distro like Ubuntu.  I'll make a fix right now.
