### ISSUE TITLE
Flowkit tag is not always tagged

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1046]
### Instructions

When releasing the flowkit/v<version> tag is not always tagged. 

### Problem

In order to reliably use flowkit tags it needs to be part of the release process

### Steps to Reproduce

flowkit/v1.1.0 does not exist

### Acceptance Criteria

Any new release of flowkit is tagged propperly

### Context

overflow

**Comment by sideninja** [comment]
Tagged
