### ISSUE TITLE
Regression in import syntax

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1047]
### Instructions

Trying to upgrade overflow to new v1.1.0 version of flowkit leads to test errors in import syntax that worked .find before. 

### Problem

Undocumented regression
### Steps to Reproduce

https://github.com/bjartek/overflow/pull/113

### Acceptance Criteria

Do not break existing import syntax that has worked before, and if we have to document how to fix it.

### Context

Overflow

**Comment by sideninja** [comment]
Looking into it. Sorry for issues.
