### ISSUE TITLE
Where are Alice's, Bob's and Charlie's keys ?

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-cli#1055]
### Instructions

After installing the Flow CLI and the VS code extension, VSCode presents the user the ability to deploy a contract to Alice.

### Problem
Who is Alice ?
Alice's account is not defined in the `flow.json` file.
If Alice, Bob, and Charlie were create by default, where are there private keys?

The VS Code extension, allows the creation on new accounts. 
I just created `Eve` but where is Eve's key?
I can't send a transaction with `flow transaction send` as Eve's key is not in the `flow.json`.

Somehow related, Flowser, also allows one to create new accounts via the Flow Dev wallet integration, but never mentions where the keys are.

### Steps to Reproduce

Install Flow CLI
Install VS Code Flow extension
Open a Flow contract in VS Code

**Comment by chasefleming** [comment]
Thanks for posting this @cybercent . Going to close this since it looks like it's being addressed here: https://github.com/onflow/vscode-cadence/issues/347
