### ISSUE TITLE
the flowkit tag is not present for v1.2.0

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1086]
### Instructions

When tagging a release please also tag the flowkit tag

### Problem

Upgrading overflow to latest flowkit still have to rely on a manual commit since it is not tagged

**Comment by chasefleming** [comment]
@bjartek is everything okay for you now?

**Comment by bjartek** [comment]
no, there are now a 1.3.0 tag aswell but no corresponding flowkit tag. That makes it hard to use flowkit as a library and version it with tags.

**Comment by bjartek** [comment]
![Screenshot 2023-06-22 at 20 58 17](https://github.com/onflow/flow-cli/assets/10621/ceea49f7-9e82-442f-8648-f75ae963f87d)

**Comment by chasefleming** [comment]
@bjartek should be updated now: https://github.com/onflow/flow-cli/tags
