### ISSUE TITLE
Command support to show linked accounts

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1115]
Currently, there is no way to see linked accounts for hybrid custody. It would be nice if you could see linked accounts using the CLI.

## Option 1

List it under the already existing accounts get command with a section for child accounts.

`flow get accounts 0x123`

## Option 2

Create a new command for child accounts:

`flow get child-accounts 0x123`

**Comment by Kay-Zee** [comment]
we could also possibly do a "--include" type flag, similar to transactions on the `get block` command

**Comment by nvdtf** [comment]
If we could run scripts from FLIX (https://github.com/onflow/flow-cli/issues/984) this can be achieved like this:
```
flow scripts execute flix/get_child_accounts 0x123 --network mainnet
```
Given `get_child_accounts` entry exists in official FLIX server pointing to https://github.com/onflow/hybrid-custody-scaffold/blob/main/cadence/scripts/hybrid-custody/get_child_addresses.cdc

**Comment by chasefleming** [comment]
Going to close this because you should be able to do this now with a FLIX script after this issue is completed: https://github.com/onflow/flow-cli/issues/984

**Comment by sideninja** [comment]
I think it's a great idea and I would strongly agree with @Kay-Zee to keep things consistent just use the `--include child-accounts` flag, or even `--include childs` and in the output you just add that as:

```
Address	 0x34ac358b9819f79d
Balance	 2146.08692171
Keys	 3003

Key 0	Public Key		 d44b801689261de92c4303c2df1ac5d36ddb86e88ac52663997c26c4d16cb1664129652afc3bc3d05b7aba3e267783a1057644454a7d449b84fc5bf77f8153e8
	Weight			 1000
	Signature Algorithm	 ECDSA_P256
	Hash Algorithm		 SHA3_256
	Revoked 		 false
	Sequence Number 	 119739
	Index 			 0

Contracts Deployed: 1
Contract: 'NFTKred'

Contracts (hidden, use --include contracts)

Child Accounts: 2 (hidden, use --include children)
``` 

Or if we want to skip checking children we can just state it's hidden without the count and then optionally do that. Also worth discussing what would the output be? Maybe it's worth keeping the same output as we have for the main account but as section for each children bellow.
