### ISSUE TITLE
--network is ignored when --host is used

### ISSUE THREAD

**Issue by ryokik** [onflow/flow-cli#1121]
If --host is specified, --network is ignored, so nothing can be deployed with the `flow deploy` command.

## Steps to reproduce

1. clone https://github.com/ryokik/example-flow-project (or `flow setup` and add some contracts)
2. Start emulator `flow emulator`
3. Deploy contracts with host option `flow deploy --host 127.0.0.1:3569 --network emulator`

<img width="781" alt="スクリーンショット 2023-07-13 12 50 49" src="https://github.com/onflow/flow-cli/assets/26475669/1e2b7131-8d81-423f-8097-fe594bfd7398">

## Additional Info
I am using jest for automated testing.
I use a different port than usual to run emulator in parallel.

Looking at the implementation, it appears that when host is specified, the internal name is "custom".
https://github.com/onflow/flow-cli/blob/daa1550168a7310426dc24d3b6e805766f470442/internal/command/command.go#L204

**Comment by ryokik** [comment]
Also, when '--host' is specified, references (imports) between Constructs cannot be resolved.
This also seems to be caused by the fact that the network name is internally set to "custom".

**Comment by sideninja** [comment]
You are right, but I wonder if you think this is a issue? the way I was thinking about is, if you have a custom host for a network you would define that in "networks" section in flow.json and then just use that network name on the deploy.

**Comment by ryokik** [comment]
I run flow emulators in parallel for automated testing.
Each has a different port.

When `--network` flag is used, I have to define networks like `emulator-1`, `emulator-2`, `emulator-3`, and the same number of duplicate deployments.
