### ISSUE TITLE
Flaky release job

### ISSUE THREAD

**Issue by jribbink** [onflow/flow-cli#1155]
### Problem

The "Build Release" GH Action seems to be somewhat unreliable.  It sometimes fails causing builds to be unavailable for certain operating systems which the build failed on.  Ex: https://github.com/onflow/flow-cli/actions/runs/5613209159/job/15249470607.  If you look through some of the recent runs of this action you will find a few that have this issue.

This is problematic if somebody doesn't notice the job failed and some of these builds are missing.

### Steps to Reproduce

Release a new version of CLI.

### Acceptance Criteria

Job passes more consistently.

**Comment by chasefleming** [comment]
Closing this as the build has been updated post this ticket.
