### ISSUE TITLE
Generate FLIX from Cadence header comment blocks (docs)

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-cli#1156]
As header comment block syntax gets solidified flow-cli can more easily generate interactive templates (flix) from Cadence. Should support Transactions and Scripts.

Current proposal:
https://github.com/onflow/flips/pull/80
soon to be on main branch in flips/interaction-template-cadence-doc

Multiple benefits for the cli supporting generate flix:
1. Help contract devs create a suit of descriptive interactions with their contracts
2. Help hand-off process with non-contract devs
3. help generate binding code for UI components to easily interact with contracts

**Comment by chasefleming** [comment]
Most of the logic for this should actually probably exist in this repo: https://github.com/onflow/flixkit-go

Then other repos can use it to insert/parse any comments as well and we can just call it from the CLI. cc. @bjartek thoughts?

**Comment by bthaile** [comment]
Moved this issue to flixkit. closing
