### ISSUE TITLE
Warning prints twice

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#116]
![Screen Shot 2021-03-19 at 5 07 59 PM](https://user-images.githubusercontent.com/901466/111852895-fed95680-88d5-11eb-8845-5ee6b9c82531.png)

Also, I can no longer get the service account information, but I assume this will be covered under "shared library" tasks?

**Comment by sideninja** [comment]
Yes, this was a quick workaround for a bug.

**Comment by sideninja** [comment]
Solved in #104
