### ISSUE TITLE
Crash on mac v1.3.4 

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-cli#1160]
### Problem

Crash on mac running `v1.3.4` installed via homebrew (`brew install flow-cli`).

This happens when running commands using the `--host` flag.

### Steps to Reproduce

Requesting the latest block using the network name works
```
$ flow blocks get latest -n mainnet 

Block ID                75301c2b44a10d8fa8695f774b1c7ea91c3c662c3ea5a91a85322c595d5bf3c8
Parent ID               75fd3b7054826c9d79bd2df076eb68b79e66087a5779268cc5b56b118c6f9f61
Proposal Timestamp      2023-08-11 18:00:21.103981919 +0000 UTC
Proposal Timestamp Unix 1691776821
Height                  58616300
Status                  Sealed
Total Seals             0
Total Collections       5
    Collection 0:       1875066d15e43a278fa96c39b0f04d2f9083ac0a7dfa7abf18226302d2418696
    Collection 1:       cea04e1c4f74ffc21ab341ece016f76e82c5cf9ee85c33a1c37a5bb2e50f141d
    Collection 2:       6703110cc3f255a27a5db881dac536485f3a9aec2bab9cc6f92ae68ab312b852
    Collection 3:       184b25962afe4f90cff23673108505eb2099ad2622693902553fe63b36154875
    Collection 4:       494e89c2aa0021b6dc84d4e77050716bca1a10c4c5488f2868d994f7db9a9247
```

Requesting the latest block using a specific host causes a crash
```
$ flow blocks get latest --host access-001.mainnet23.nodes.onflow.org:9000 

❌ Crash detected! 

Use the arrow keys to navigate: ↓ ↑ → ← 
? 🙏 Please report the crash so we can improve the CLI. Do you want to report it?: 
  ▸ Yes, report the crash
    No
```

I'm guessing it's related to this recent change, but not totally sure:
https://github.com/onflow/flow-cli/compare/v1.3.3...v1.3.4#diff-69d3575d337e6861d23e877e04bbdb99f437a82661f706f055a50e82b1e8282aR203

**Comment by peterargue** [comment]
This appears to be related to having a missing `flow.json` file in the path. Previously, I did not have an effective `flow.json`. After running `flow init` in my home directory, it stopped crashing.

thanks @bjartek and @jribbink for your help debugging

**Comment by bjartek** [comment]
```_, err := state.Networks().ByName(networkFlag)
		if err != nil {
			return nil, fmt.Errorf("network with name %s does not exist in configuration", networkFlag)
		}```
		
My guess is that this is where it fails. 

in command.go when loading configuration it is allowed to not have a config file, but then on the presecing line resolveHost is called that requires a valid configFile/state.

**Comment by jribbink** [comment]
I just debugged it and it's a null pointer dereference.

It was introduced in this commit https://github.com/onflow/flow-cli/commit/3af5cf585bd32b37219d74cf5b42a00e3b3cd148.

I'll try to make a fix
