### ISSUE TITLE
Cannot retrieve block from a previous access node 

### ISSUE THREAD

**Issue by AlexandreBarbier** [onflow/flow-cli#1172]
### Problem
I'm trying to retrieve blocks from access-001.mainnet1.nodes.onflow.org:9000.
Everything goes well until I reach this height 7652359. At this height and the following the api return a Not found error.
If I use a previous version of the cli, I'm able to retrieve the block but not with the latest version (cf: screenshot below).

### Steps to Reproduce
You can use two different version of the cli to reproduce the bug and see that it was working in version 1.3.3 of the cli and not in the version 1.3.4

<img width="1550" alt="Screenshot 2023-08-28 at 15 25 28" src="https://github.com/onflow/flow-cli/assets/1663580/2c8b4302-a880-42a2-98d2-c33819b4dfab">

### Context
I need to retrieve transactions from those block.

**Comment by chasefleming** [comment]
This looks like it may be the same issue as this: https://github.com/onflow/flow-cli/issues/1160

A fix for that issue has been merged and will be out next release.
