### ISSUE TITLE
Error on unsafeRandom() call in v1.3.4+

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-cli#1174]
### Problem

Calls to `unsafeRandom()` result in error. Bug persists in 1.3.4 & 1.4.0.

### Steps to Reproduce

Execute the following script with the CLI versions 1.3.4 or 1.4.0

```cadence
pub fun main(): UInt64 {
    return unsafeRandom()
}
```

Which will result in the following error:

```
❌ Command Error: client: rpc error: code = Unknown desc = [Error Code: 1057] error caused by: 1 error occurred:
	* [Error Code: 1101] cadence runtime error: Execution failed:
error: internal error: [Error Code: 1057] operation (Random) is not supported in this environment
```

### Acceptance Criteria

The unsafeRandom API is still active (though [undergoing refactor](https://github.com/onflow/flips/pull/120/files?short_path=88fbf10#diff-88fbf106dd5168e38ceeb89dd8ef9d8dacd932b05c5b7720db2a8e619e673610)) so the call should function as it does with version 1.3.3 and older.

### Context

Not currently blocked - using v1.3.3 instead - but came up when running Cadence tests locally.

**Comment by chasefleming** [comment]
@turbolent should this be supported after this PR? https://github.com/onflow/flow-cli/pull/1158

**Comment by turbolent** [comment]
Needs onflow/flow-emulator#459

**Comment by turbolent** [comment]
cc @tarakby

**Comment by tarakby** [comment]
Although I triggered the issue on `flow-go` and then made a fix on `flow-emulator`, I have no visibility on emulator releases. Perhaps we could tag the emulator or Devex tools owner?

**Comment by btspoony** [comment]
Can we have a new release of Emulator for https://github.com/onflow/flow-emulator/pull/459 to fix this?
