### ISSUE TITLE
What is missing in flow.cli

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#120]
This is a little rant I wrote down after looking at the state of flow.json 

- I do not see the need for the emulators block, networks are sufficient to emulate all the use cases I can see
- in accounts the work chain is used but the chain resource does not exist. Should this be networks? How do you map the key of an accounts chain to something? It is not intuitive
- when you create a flow.json there are a lot more things that should be preopopulated
  - all standard accounts on all networks 
  - all networks
  - it should prompt you if you want to create more test emulator accounts and just prefill them in for you since you can use the same keys as the emulator-account and a fixed list of accounts
-  the emulator should be able to work even if you do not have the local files if the contracts are in accounts

**Comment by sideninja** [comment]
> I do not see the need for the emulators block, networks are sufficient to emulate all the use cases I can see

We actually didn't have it in the first implementation but add it as it might contain some other properties in future (like settings for emulator - `enable fees` etc...)

> in accounts the work chain is used but the chain resource does not exist. Should this be networks? How do you map the key of an accounts chain to something? It is not intuitive

Chain ID is going away 💯  %, I was now working on a huge refactor and after that this will be one of the first thing to make sure it's not specified.

> when you create a flow.json there are a lot more things that should be preopopulated
> - all standard accounts on all networks

Hmm, what other standard accounts you have in mind here beside the service account for emulator which is already there?

> all networks

Great idea :)

> it should prompt you if you want to create more test emulator accounts and just prefill them in for you since you can use the same keys as the emulator-account and a fixed list of accounts

Yeah I had similar conversation with @MaxStalker and to be honest I'm not sure about it still, even though from the UX perspective I agree it can be beneficial to have accounts automatically generated I'm afraid due to the nature of how Flow generates account on the network it could present some weird cases - like maybe accounts would already be created by someone else (maybe your script or smth), but please share your idea of implementing this

> the emulator should be able to work even if you do not have the local files if the contracts are in accounts

Are you talking about deploying here?

One feature with this new refactor I'm excited about is that you would be able to run "hosted" emulator, so you will be able to use a flag with the command and the emulator will be created inside CLI so you don't have to create it as a separate process. 

Thank your for your feedback, always appreciated :)

**Comment by bjartek** [comment]
> > * all standard accounts on all networks
> 
> Hmm, what other standard accounts you have in mind here beside the service account for emulator which is already there?

I am sorry my brain did not work here, i mean that the address for all the standard contracts should be populated.

FlowFees=0xe5a8b7f23e8b548f FlowServiceAccount=0xf8d6e0586b0a20c7 FlowStorageFees=0xf8d6e0586b0a20c7 FlowToken=0x0ae53cb6e3f42a79 FungibleToken=0xee82856bf20e2aa6


> > it should prompt you if you want to create more test emulator accounts and just prefill them in for you since you can use the same keys as the emulator-account and a fixed list of accounts
> 
> Yeah I had similar conversation with @MaxStalker and to be honest I'm not sure about it still, even though from the UX perspective I agree it can be beneficial to have accounts automatically generated I'm afraid due to the nature of how Flow generates account on the network it could present some weird cases - like maybe accounts would already be created by someone else (maybe your script or smth), but please share your idea of implementing this

I guess I can just stick to my flow (nice pun huh) that i use with go-with-the-flow. I have an extra key emulatorAccounts in the flow.json and can create those uses as local accounts in the emulator and use the addresses in my DSL when I create transactions. 

> > the emulator should be able to work even if you do not have the local files if the contracts are in accounts
> 
> Are you talking about deploying here?

Sorry again I was unclear. I mean the VSCode extentsion. If I import a contract that is on emulator as a path but I do not have that path in my filesystem then I get an error in vscode. This will confuse users who are less savvy.


> One feature with this new refactor I'm excited about is that you would be able to run "hosted" emulator, so you will be able to use a flag with the command and the emulator will be created inside CLI so you don't have to create it as a separate process.

So you are saying that there will be a command that starts the emulator and then deploy contracts to it? That would be nice, but unless more of my needs are met I still need a seperate tool. In order to create new accounts, replace address in transactions and scripts. 

What I really want to do is replace this https://github.com/bjartek/go-with-the-flow/blob/master/examples/demo/main.go with something that only uses the flow cli. Now that could very well be a bash script, or just go like it is here.

**Comment by sideninja** [comment]
> FlowFees=0xe5a8b7f23e8b548f FlowServiceAccount=0xf8d6e0586b0a20c7 FlowStorageFees=0xf8d6e0586b0a20c7 FlowToken=0x0ae53cb6e3f42a79 FungibleToken=0xee82856bf20e2aa6

I like this idea, I would add this as aliases in the contracts section. 

> I guess I can just stick to my flow (nice pun huh) that i use with go-with-the-flow. I have an extra key emulatorAccounts in the flow.json and can create those uses as local accounts in the emulator and use the addresses in my DSL when I create transactions.

I'm still torn about this. One side of me wishes to add this so users have the best UX with already created accounts, the other side of me is afraid we will make CLI too opinionated (maybe people will use it more for deployment on mainent etc). I think this is great that is here and I will try to gather more feedback from the community before proceeding. I'm now in the process of analyzing what people say CLI lacks or have problem with.

> Sorry again I was unclear. I mean the VSCode extentsion. If I import a contract that is on emulator as a path but I do not have that path in my filesystem then I get an error in vscode. This will confuse users who are less savvy.

This is something that is more related to vscode extension than CLI, however we have made sharedlib for CLI and vscode both to use, but still something that should be addressed under vscode extension issue.

> So you are saying that there will be a command that starts the emulator and then deploy contracts to it? That would be nice, but unless more of my needs are met I still need a seperate tool. In order to create new accounts, replace address in transactions and scripts.

Actually emulator will be run in the same process, so there won't be a separate process for emulator which will listen on a port but it will be ran as part of the CLI process. But that doesn't address the problem with replacing addresses in transactions and scripts, which is in the top priority and will start working on that issue soon.

**Comment by bjartek** [comment]
Regarding replacing addresses inn transactions and scripts. Will this work for parameters as well? I guess maintaining a different parameter file for different networks works. Feel feee to link the issue and I can comment there.

**Comment by sideninja** [comment]
> Regarding replacing addresses inn transactions and scripts. Will this work for parameters as well? I guess maintaining a different parameter file for different networks works. Feel feee to link the issue and I can comment there.

Would you mind opening one? I haven't yet open and made a proposal and I think it makes sense if you write and I can comment :) 

Also if you will have time take a look at #124

**Comment by bjartek** [comment]
Willdo.

**Comment by sideninja** [comment]
I've created two separate issues each describing related problems so we can divide and conquer:
- pre-populated configuration: #125 
- existing accounts: #126 

I'm closing this issue in favor of those issues.
