### ISSUE TITLE
Missing deployments section stops script execution

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1201]
You can add a contract with `flow accounts add-contract ./HelloWorld.cdc --network emulator --signer test-acct`, but if I go to run a script against it with `flow scripts execute script.cdc --network emulator` I will get the following error:

`Command Error: import HelloWorld could not be resolved from provided contracts`

If I add a deployments section it goes away. Note: this only happens with the new import syntax of `import "HelloWorld"`

Technically it should work without the deployments section since the contract is already deployed.

**Comment by bjartek** [comment]
I belive add-contract was added before there was `flow deploy` is this this really an command we need?

**Comment by chasefleming** [comment]
I can see use cases for wanting to deploy individual projects vs the entire project with `flow deploy`. I'd vote for keeping it. But yeah if there are issue we should solve them...which it looks like you just PR'd. Thanks for doing that. Will take a look.
