### ISSUE TITLE
Add a command for funding an account on testnet

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1213]
Having to manually add your address to fund an account from the [Faucet site](https://testnet-faucet.onflow.org/fund-account) while developing is a little tedious. It would be nice if you could run a command like the following to fund an account:

`flow fund testnet-acct`

This would take the account from your flow.json and send it 1000 like on the Faucet site. We could also add a `--amount` flag if the dev wanted to customize the amount but it could also be added later. Not sure the flag is necessary.

Note: should error with a message if you try to fund an account that isn't testnet.

**Comment by ianthpun** [comment]
@bthaile mind if i take this?
