### ISSUE TITLE
Command restructure

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#124]
Commands could be restructured and improved. 

Commands should also be autocompleted to avoid typing every time. Cobra has a good support for this https://github.com/spf13/cobra#generating-shell-completions

Possible command restructure for CLI:

## Accounts

Nothing really changes here.

```json
accounts get
accounts create
accounts staking-info
```

## Contracts

A new section which I think makes sense because contract is a concept expected from other blockchains to be separated from accounts and I think if we put it in the first level command it will be more visible to users how to deploy contract (I saw this question 2 times already - how to deploy a contract - oh it's under accounts).

```json
contracts deploy
contracts update
contracts remove
```

## Transactions

Nothing really changes here.
Maybe provide a short option for transactions to be `tx`, although this will also be improved with autocompletions.

```json
transactions send
transactions get
```
possible shorthand:
```json
tx send
tx get
```

## Keys

Nothing really changes here.

```json
keys generate
keys decode
```

## Project

Adding project manipulation methods. I strongly believe this is a must. Also Bjartek said mulitple times and opened a PR on add contract but this goes further, we should allow adding all resources to the config via command.

```json
project init
project deploy
project add <account|contract|deployment|network>
project remove <account|contract|deployment|network>**  
```

There should also be a guided prompt way to add resources, let me give an example:

```json
project add deployment
Contracts in the configuration:
[0] FungibleToken
[1] Kibble
[2] KibbleMarket
Choose the contract for deployment: 1

Networks in the configuration:
[0] Emulator
[1] Testnet
[2] Mainnet
Choose the network for deployment: 1

✅ Contract **Kibble** will be deployed to **Testnet** when you run **flow project deploy**
```

## Top Level Commands

Maybe we can flatten commands that have only 1 subcommand either in the following format:

```json
get-block
get-collection
start-emulator
execute-script
```

or maybe with the following format - where singular verb is actual top level command

```json
block
collection
emulator
script

example
block 120025 (would fetch that block)
```

**Comment by bjartek** [comment]
I like the form CMD verb subject. But CMD subject verb works as well. I would not prefer CMD verb-subject.

The reason i like this is because it makes tab completion so nice flow get<tab> will list out all you can get aso.

There are lots of clis that use this like kubectl.

**Comment by bjartek** [comment]
Are you familiar with how kubectl work here? I would look there for inspiration.

**Comment by sideninja** [comment]
> Are you familiar with how kubectl work here? I would look there for inspiration.

Yep, I did. I think with tab completions it makes sense to not shorten it as new subcommands might be added which would break the structure down the line

**Comment by sideninja** [comment]
Update on restructuring.

## Init 
Initialization shouldn't be part of `project` subcommand as config is used from other CLI commands too. It should be put in the top level as `flow init`.

However, this opens few more questions. As `flow init` is the top command it's now hard to find a place for commands that modify the configuration. One idea is to create top-level `config` command and have subcommands for modifying config such as:

```
config add <account|contract|deployment|network>
config remove <account|contract|deployment|network>
config init (aliased with flow init) 
```

This `flow init` alias also opens a new door of having frequent commands aliased and improve UX and make it pretty.

Maybe aliases commands could even be separated in help section so it could look like:

```
Usage:
  flow [command]

Hot Commands:
  init       Initialize configuration
  deploy     Deploy project
  run        Start emulator and deploy contracts

Available Commands:
  accounts     Utilities to manage accounts
  blocks       Utilities to read blocks
  cadence      Execute Cadence code
  collections  Utilities to read collections
  emulator     Starts the Flow emulator server
  events       Utilities to read events
  help         Help about any command
  keys         Utilities to manage keys
  project      Manage your Cadence project
  scripts      Utilities to execute scripts
  transactions Utilities to send transactions
  version      View version and commit information
  config       Configuration commands
```

**Comment by bjartek** [comment]
Looks great to me :)

**Comment by psiemens** [comment]
@sideninja I really like this proposed structure now that I'm seeing it written down.

The `config` subcommand group makes a lot of sense to me 👍

**Comment by bluesign** [comment]
I am using like this long time, so I have some comments. 

Variables are not showing up (ex: flow accounts get address), I think can be related to making it required parameter maybe, I didn't have much time to check. 

Also some global flags should not show I guess (for example: --network on flow keys generate) 

[0] https://asciinema.org/a/d9scOA3BmlGdxhQwgJOSZoGNN
