### ISSUE TITLE
FLIX package doesn't create directory to save in

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1253]
When running `flow flix package multiply.template.json --save foo/bar/multiply.js` it does not create the directories.

```
❌ Output Error: open foo/bar/multiply.js: no such file or directory
```

If I do `flow flix package multiply.template.json --save multiply.js` it works fine.

**Comment by bjartek** [comment]
I think we shoukd fix —-save so that it creates directories.
