### ISSUE TITLE
Scaffold a specific project template with `--scaffold={id}`

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-cli#1271]
### Issue To Be Solved

Currently, you can only scaffold a project in "interactive mode" with `--scaffold` flag.

This isn't ideal for these reasons:
- makes it harder to provide instructions in the documentation (e.g. start by scaffolding X project)
- makes it hard to reuse `flow setup --scaffold` by 3rd party tools
- nit: more work if you already know which project to scaffold (in case you are doing that repeatedly when playing around, etc...)

For example, the bellow instructions from [hybrid custody scaffold repo](https://github.com/onflow/hybrid-custody-scaffold#-start-developing) could be shortened to just one step: `flow setup --scaffold=hybrid-custody`.

![Screenshot 2023-11-15 at 10 38 22](https://github.com/onflow/flow-cli/assets/36109955/9cded28c-bca3-4ef8-94fc-ea8aa2f2a6f2)

### Suggest A Solution

Make the `--scaffold` flag optionally accept a scaffold ID argument. If that argument is present, immediately scaffold that project instead of launching the interactive scaffold flow.

This would also require adding an `id` field to the scaffolds json: https://github.com/onflow/flow-cli/blob/master/scaffolds.json

### Context

We are thinking of better streamlining project creation within Flowser. A part of that is also enabling users to scaffold new projects easily within Flowser itself. We could implement our scaffolding logic, but it could be even better to just reuse the Flow CLI `setup` command for this. And other tools or users could also benefit from this change.

**Comment by chasefleming** [comment]
@bartolomej This sounds like a nice feature. It might be better to use the flags built into Cobra though and do `id` as a flag so the command would be `flow setup foo --scaffold --id 2`. Would be easier than splitting and parsing the name following the `=`. So you're also suggesting using a new id field? What do you see as the benefit of introducing that vs just using the number you currently select as an index?

**Comment by bartolomej** [comment]
@chasefleming Hmm I see. Although it is a bit weird having separate flags like that. Would that imply you can use just the `--id` one without the `--scaffold`? If not, it may be kinda confusing to say "`id` can only be used with `scaffold` flag", but maybe not.

I was thinking introducing a new ID field might be better because:
- it's easier to use and make sense of (seeing `--scaffold=hybrid-custody` in the docs is easier to make sense of than `--scaffold=3`)
- it's maybe a bit safer to define the ID explicitly, instead of relying on the ordering of scaffolds in a JSON file (assuming that determines the index you are talking about above). Otherwise, we'd always need to make sure to put new scaffold objects at the end of scaffolds.json.

**Comment by bjartek** [comment]
It would also be very nice to use a scaffold that is not in the registry. like 
```flow setup mystuff --scaffold --repo bjartek/mystuff``` or something like that.

**Comment by bjartek** [comment]
What about an alternative to a central registry where users can define topic that can be used to discover thing? If i add the topic `onflow-scaffold` to my repo i can get all things with that topic in the suggestion? Or maybe even have sub topics like onflow-scaffold-backend or things like that.

**Comment by bluesign** [comment]
On this note it would be nice to allow more interactive scaffolds. ( which can also be run with some kind of cli args ) 

If I want to setup some `basicNFT` scaffold, it can also ask me something like, if I want to setup a storefront too.

**Comment by chasefleming** [comment]
@bjartek what benefit would the setup get you that just `git clone` a repo you want doesn't get you? The only fear I have about having too many scaffolds is that if they aren't constantly checked and maintained they can get out of date really quick. Which could leave a dev with a bad first experience if they go to clone something that isn't maintained.

And yeah @bartolomej your idea about some sort of naming make sense so that you don't have to rely on order. Although we'd have to make sure no one named something the same thing.
