### ISSUE TITLE
Sending a transaction with a non-existing signer account causes a runtime error in the CLI.

### ISSUE THREAD

**Issue by appleweed** [onflow/flow-cli#131]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Executing any valid transaction with a non-existing signer account will cause a runtime error.

### Steps to Reproduce

1. Choose a simple transaction script.
2. Attempt to send using the CLI: flow transactions send --code ./YourTransaction.cdc --signer InvalidAccount --host localhost:3569
3. You will see the following runtime error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c92e86]

goroutine 1 [running]:
github.com/onflow/flow-cli/flow/transactions/send.validateKeyPreReq(0x0)
	github.com/onflow/flow-cli/flow/transactions/send/send.go:109 +0x26
github.com/onflow/flow-cli/flow/transactions/send.glob..func1(0x5c877c0, 0xc00013fb00, 0x0, 0x6)
	github.com/onflow/flow-cli/flow/transactions/send/send.go:56 +0x9a
github.com/spf13/cobra.(*Command).execute(0x5c877c0, 0xc00003c0c0, 0x6, 0x6, 0x5c877c0, 0xc00003c0c0)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x5c87fa0, 0x0, 0x5a6b068, 0xc00010e058)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/onflow/flow-cli/cmd/flow/main.go:62 +0x2d
```

### Acceptance Criteria

Should execute the transaction, and if valid, run to completion; or, the transaction should fail normally without a CLI runtime error.

### Context

This does not occur if the signer is a valid account. So this does not block, per se.

**Comment by sideninja** [comment]
Fixed in version v0.17.0
