### ISSUE TITLE
Fix broken build and address cross compilation

### ISSUE THREAD

**Issue by tarakby** [onflow/flow-cli#1341]
### Problem

Current release build on master is broken after importing the latest version of the crypto package. The new crypto package version requires `CGO` to be enabled and requires specifying the correct C compiler for cross-compilation (the new crypto version uses portable and non-portable code). The current CI build cross compiles on the same machine for [multiple targets](https://github.com/onflow/flow-cli/blob/cba2729/.github/workflows/build-release.yaml#L10-L18). 
For now, a workaround is to use the old crypto version (which uses go build tags to not include the non-portable code part). This issue aims to solve the cross-compilation properly with a proper solution.

cc @sideninja

**Comment by chasefleming** [comment]
This has been fixed by: https://github.com/onflow/flow-cli/pull/1423
