### ISSUE TITLE
Retry when ratelimited 

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1367]
### Issue To Be Solved

When interacting through flow you have to now handle rate limits as the new limits are way more agressive then what they used to be. Having to modify client code to add that is quite the effort. 

### (Optional): Suggest A Solution

When interacting with the flow chain through flowkit it would be nice to be able to automatically retry requests that fail due to rate-limiting using set policies.

Would it be an option when creating a flowkit.State to add some policies for retrying, and have those only retry on 429. 

This library for instance is really flexible around retry and it is not specific to http/grpc. 

https://github.com/avast/retry-go

**Comment by chasefleming** [comment]
@bjartek is the rate limiting happening when you're using CLI commands or when you use `flowkit` in an application or library?

**Comment by chasefleming** [comment]
Awesome, yeah I was going to say maybe it should just be a config in flowkit then if it's at a library level.

**Comment by chasefleming** [comment]
@bjartek can this be closed now?

**Comment by bjartek** [comment]
Yes
