### ISSUE TITLE
Recent EVM contract is missing from CLI

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-cli#1385]
### Problem

The [EVM contract](https://contractbrowser.com/A.8c5303eaa26202d6.EVM) recently deployed to Testnet is not included in the CLI. Release [1.8.0-evm.preview.2](https://github.com/onflow/flow-cli/releases/tag/v1.8.0-evm-preview-3) contains the full EVM contract, but is coupled with Cadence 1.0.

### Acceptance Criteria

A CLI release with the current version of Cadence including automated deployment of the EVM contract when emulator is started.

### Context

Affecting Axelar integration tests

**Comment by chasefleming** [comment]
@sisyphusSmiling Is this still an issue?

**Comment by sisyphusSmiling** [comment]
Yeah, @sideninja mentioned he updated emulator for a CLI release that would include Cadence 0.42 + EVM contract currently on TN/MN
