### ISSUE TITLE
Add `flow cadence lint` command

### ISSUE THREAD

**Issue by jribbink** [onflow/flow-cli#1395]
## Instructions

Please fill out the template below to the best of your ability.

### Issue To Be Solved

Currently, the [Cadence linter](https://github.com/onflow/cadence-tools/tree/master/lint) is only really surfaced through the language server & adjacent tools (VSCode extension, playground).  It is a valuable static-analysis tool which could be a part of automation processes and developers may want to run it independently (outside of integration with the aforementioned tooling).

We should surface this as a command in the Flow CLI so that developers can enforce better standards within their Cadence code and catch errors earlier in their development cycle.

### (Optional): Suggest A Solution

Add a `flow cadence lint <files>` command which runs all linting analyzers as and surfaces these to the output.  The command should also attempt to surface any parsing/checking errors in a structured format.

### (Optional): Context

This relates to efforts related to Cadence 1.0 and helps developers understand if problems exist in their code, what these problems are, and how they can attempt to mediate them.

related: https://github.com/onflow/cadence-tools/pull/285

**Comment by turbolent** [comment]
That would be great! Similarly, it would be great to expose the docgen tool and the test tool (might already be not sure)
