### ISSUE TITLE
Cadence 1.0 notice broken migration guide link

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-cli#1400]
### Problem

The current 1.0 notice redirects to a 404

```
                           ⚠ Upgrade to Cadence 1.0                           
     The Crescendo network upgrade, including Cadence 1.0, is coming soon.     
     You may need to update your existing contracts to support this change.     
                     Please visit our migration guide here:                     
           https://developers.flow.com/build/cadence-migration-guide           
```

redirecting to https://cadence-lang.org/docs/cadence-migration-guide which results in 404

### Steps to Reproduce

Run a cli command like `flow version` (I did so using 1.13.0) and find the notice mentioned above. Click on the link and find the redirect.

### Acceptance Criteria

Output to live link, currently https://cadence-lang.org/docs/cadence_migration_guide

**Comment by chasefleming** [comment]
@sisyphusSmiling can you post this on the docs repo please if the issue is the redirect?

**Comment by chasefleming** [comment]
Issue: https://github.com/onflow/docs/pull/557

**Comment by chasefleming** [comment]
Looks like a docs redirect issue. Fixed here: https://github.com/onflow/docs/pull/557
