### ISSUE TITLE
Move migrate to flowkit

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1464]
### Issue To Be Solved
Migrate is implemented in internal package and it is thus impossible to compose upon it in other tools. All of the state it depends upon is in flowkit, so it should be in flowkit

### (Optional): Suggest A Solution
Move it to flowkit

### (Optional): Context

Testing migrations of contracts using overflow

**Comment by ianthpun** [comment]
i'll take this

**Comment by ianthpun** [comment]
Given the migration is atually somehting that will be scrapped post-crescendo, im thinking we can just keep it here and remove it once its finished. I'd like to keep flowkit as core as it gets, unless its blocking you somehow @bjartek ?

**Comment by chasefleming** [comment]
Closing this for now. Let me know if you need it @bjartek and it should be reopened.
