### ISSUE TITLE
Add some dependency versions to the CLI

### ISSUE THREAD

**Issue by jribbink** [onflow/flow-cli#1465]
### Issue To Be Solved

When using a given version of the Flow CLI, it's not particularly obvious what versions of various components you are using under the hood.  Most critically, with the Cadence 1.0 rollout & tons of preview releases, it's hard to know which version of Cadence or flow-go you are using.  These two versions are especially important to surface in the CLI.

### (Optional): Suggest A Solution

Add this information to `flow version`.  Arguably it's an important component of versioning information in the CLI so I think it is reasonable to include some of our most important upstream Flow dependencies here.  It doesn't necessarily need to be everything, but I think these two are a good start.

should be very easy: https://stackoverflow.com/a/62009359

### (Optional): Context

https://discordapp.com/channels/613813861610684416/1219577974140174427/1219624498370711632

**Comment by ianthpun** [comment]
i'll take this one
