### ISSUE TITLE
Add command to pull staged contract status

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-cli#1508]
### Issue

Currently, `flow-c1 migrate is-validated` pulls the contract status from the on-chain repository.  However, this is not currently being populated and there are no existing plans to do so, so we need to determine a workaround

### Suggested solution

Add cli command to allow user to pull current status from the published GitHub report on https://github.com/onflow/cadence repository, as this is where the reports are currently being published

**Comment by jribbink** [comment]
closed by https://github.com/onflow/flow-cli/pull/1529
