### ISSUE TITLE
previewnet chain not known to dependency manager

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#1592]
### Problem

Trying to install a dependency from previewnet fails

### Steps to Reproduce

```
flow-c1 init
```
add the following to the json 
```

  "dependencies": {
    "FiatToken": "previewnet://7e3499582a06616f.FiatToken"
  }

```

run `flow-c1 dependencies install`

❌ Crash detected! unknown chain:

### Acceptance Criteria

It is possible to install dependencies from previewnet

### Context

cadence 1.0

**Comment by chasefleming** [comment]
This should just need a flowkit bump now and release to be fixed.
