### ISSUE TITLE
flow init should add previewnet to flow.json and create a .gitignore

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-cli#1646]
### Issue To Be Solved

I tried `flow init` saved me an hour, it is amazing.
It would be nice to add previewnet to flow.json and create .gitignore for keys

**Comment by chasefleming** [comment]
Awesome! That's so great to hear. Previewnet should be on there when it's created on the stable cadence branch. Do you need it on master? And yes to the gitignore for keys. Great idea.

**Comment by bluesign** [comment]
ah I think this was my bad, I created config with `flow init` then tried to use it with `flow-c1 dev` or something. I got error something like: `contract EVM alias contains nonexisting network previewnet` 

`flow-c1 init` was not interactive somehow.
