### ISSUE TITLE
Standard value for emulator flag and possibility to change the standard using and ENV var

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#170]
### Issue To Be Solved

`flow project deploy` does not work anymore since the new -n flag does not have a default. 

### (Optional): Suggest A Solution

- network should have a default value set to emulator
- implement a way to change this default value using an ENV_VAR or a value in flow.json

**Comment by sideninja** [comment]
Good catch. I've already solved this in an open PR #161 which will be released next week.

**Comment by sideninja** [comment]
PR #161
