### ISSUE TITLE
flow-c1 cli  create account interactive

### ISSUE THREAD

**Issue by AliAsMath** [onflow/flow-cli#1707]
### Problem

flow-c1 version 1.21.0 for create accounts not working properly. I want to create account interactive but it throw an Error that is "Command Error: You provided flags, but no key. A key is required to create an account in manual mode. Remove flags if you'd like to use interactive mode." but i dont use any flag

flow-c1 accounts create

**Comment by AliAsMath** [comment]
please check this

**Comment by turbolent** [comment]
@AliAsMath Are you trying to create an account for Mainnet? This is not supported. If that's the case we can close this issue as a duplicate of #1262, proposes to improve the UX around this.

**Comment by chasefleming** [comment]
Closing. Should be resolved.
