### ISSUE TITLE
Flow project deploy

### ISSUE THREAD

**Issue by david03g** [onflow/flow-cli#172]
```
Deploying 0 contracts for accounts: 


✨  All contracts deployed successfully
```

When running "flow project deploy" in the command line 0 contracts get deployed even though flow.json is properly configured. I am running in a Mac terminal. 

Others have had the same issue

**Comment by david03g** [comment]
You have to specify the network, which was not clear 

`flow project deploy --network=emulator`

**Comment by sideninja** [comment]
The next release will include a default value for the network and this issue will be avoided, but it is a valid issue.
