### ISSUE TITLE
Include previewnet when creating a fresh flow.json file with flow init

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-cli#1724]
### Issue To Be Solved

When you create a flow.json file using cli, it doesn't includes previewnet under networks, but later when you use the dependency manager for adding contracts such as NonFungibleToken, it will specify an alias for that network, resulting in a bad flow.json

### Suggest A Solution

If this is related to the C1 upgrade just close and ignore it, if previewnet if going to stay, just add it to the networks object when creating a fresh flow.json file

**Comment by btspoony** [comment]
I think all previewnet related stuff need to be removed in `flow-cli` 
Input hint of previewnet in the dependency manager is also annoying
@chasefleming

**Comment by chasefleming** [comment]
Yep, correct. Previewnet is in the process of being removed. The latest version should solve some previewnet related issues.
