### ISSUE TITLE
Dotenv support

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#179]
### Issue To Be Solved

It would be nice if the CLI could read from a `.env` file in the active directory.

### Suggest A Solution

This library could be used: https://github.com/joho/godotenv

**Comment by sideninja** [comment]
I can add support for this. But what it should read and in which case those values should be used?

**Comment by psiemens** [comment]
Sorry, should have elaborated! 

I'm just thinking of something very simple. Any environment variables declared in a `.env` file in the active directory (the directory where the CLI is being invoked) would be added to the environment before each CLI command executes.

For example, as long as `godotenv.Load()` is called before `os.Environ()` is accessed, then `os.Environ()` should be populated with all of the values from `.env`.

The `envsubst` package uses `os.Environ()` under the hood, so this should allow vars from `.env` to be included in the `flow.json` config files.

```go
// .env file is optional, so we shouldn't error if it doesn't exist
_ := godotenv.Load()

// ..

updatedConfig, _ = envsubst.String(config)
```

For Kitty Items, for example, this enables:

```
// .env (gitignored)
FLOW_ADDRESS=0xdedabeef
FLOW_PRIVATE_KEY=xxxxxxxxxx
```

`.env` is also common for Nodejs apps, so would allow both the CLI and JS apps to read from the same config file

```js
// flow.json
// ...
  "accounts": {
    "emulator-account": {
      "address": "0xf8d6e0586b0a20c7",
      "keys": "11c5dfdeb0ff03a7a73ef39788563b62c89adea67bbb21ab95e5f710bd1d40b7"
    },
    "testnet-account": {
      "address": "${FLOW_ADDRESS}",
      "keys": "${FLOW_PRIVATE_KEY}"
    }
  }
// ...
```

**Comment by 10thfloor** [comment]
Can we close this?
