### ISSUE TITLE
Sending a transaction shows different IDs

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-cli#190]
### Instructions

When sending a transaction, the output shows different IDs, not sure why:

```
Sending transaction with ID eddb3dd6f10fabf6873d1578306722dd510d4b21fd00c5757a8aee3a67e3e48c

ID	 1cff804f008c5618dd8b7fe77382d90d6f713058c91cc1275fdcc1c6d9a626a1
Status	 SEALED
Payer	 16fdd39a7bf5afd6
Events
	 Index	 0
	 Type	 A.7e60df042a9c0868.FlowToken.TokensWithdrawn
	 Tx ID	 1cff804f008c5618dd8b7fe77382d90d6f713058c91cc1275fdcc1c6d9a626a1
	 Values
		 amount (UFix64)	1.00000000
		 from ({}?)			16fdd39a7bf5afd6
```

### Problem

The first ID (`eddb3dd6f10fabf6873d1578306722dd510d4b21fd00c5757a8aee3a67e3e48c`) seems to be wrong, the second ID is valid (`1cff804f008c5618dd8b7fe77382d90d6f713058c91cc1275fdcc1c6d9a626a1`).

### Steps to Reproduce

-

### Acceptance Criteria

IDs should be consistent and valid

**Comment by sideninja** [comment]
This is also fixed in the new pending PR, however there it was removed to just say "sending transaction...", but I added it back to say "sending transaction with id" and it is now correct ID. Before it was wrong because it showed ID before transaction was signed.

**Comment by turbolent** [comment]
Awesome! 👍
