### ISSUE TITLE
flow key generate -o json switched around keys

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#193]
### Problem

 flow keys generate
🔴️ Store private key safely and don't share with anyone!
Private Key 	 e944c6f6eccac0442e15d8ffd62695526a8a2674baa8fb6398fb874a99572296
Public Key 	 3aed575c209e5b7ed2534e80333e98bd3cacc89b98783ed81477d781d800d561473782f851688745b396a8bd6f8a1a51ecbff0344157de411e37451178678c8a

flow keys generate -o json
{"private":"27c375ead20050f2977bc972a787be9f270b3bd88e693975bf43f87eaa0d39e22bd9d8f1c939925041e60edd9a8f3cc9390efc56d86f3e78340f8c34f2a491ce",
"public":"459a584c3ccc72ab766e4533529fb492b853d10e7bd426002ed8a945288c77c8"}

In the json output the keys have been switched around, the short key is the private key but it is named public.

**Comment by sideninja** [comment]
Thank you for reporting this, fix is pending.
