### ISSUE TITLE
flow project deploy with wrong account

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#194]
### Problem

flow.json has an account under deployments/emulator that is not present in the flow.json file for that network

flow project deploy -n emulator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4a24b5a]

goroutine 1 [running]:
github.com/onflow/flow-cli/pkg/flowcli/project.(*Project).ContractsByNetwork(0xc00014c3f0, 0x7ffeefbff9e7, 0x8, 0xc000387af0, 0x40105e8, 0x4fb7f80)
	github.com/onflow/flow-cli/pkg/flowcli/project/project.go:187 +0x31a
github.com/onflow/flow-cli/pkg/flowcli/project.(*Project).ContractConflictExists(0xc00014c3f0, 0x7ffeefbff9e7, 0x8, 0x15)
	github.com/onflow/flow-cli/pkg/flowcli/project/project.go:133 +0x45
github.com/onflow/flow-cli/pkg/flowcli/services.(*Project).Deploy(0xc00014cc30, 0x7ffeefbff9e7, 0x8, 0xc000617c00, 0xc00014cba0, 0xc00014cbd0, 0xc00014ccc0, 0xc00014cc00, 0xc00014cb10)
	github.com/onflow/flow-cli/pkg/flowcli/services/project.go:104 +0x6c
github.com/onflow/flow-cli/internal/project.glob..func1(0x5c3d7c0, 0xc000138fe0, 0x0, 0x2, 0x0, 0x0, 0x50042c5, 0x4, 0x0, 0x0, ...)
	github.com/onflow/flow-cli/internal/project/deploy.go:47 +0x5b
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x5c3d7c0, 0xc000138fe0, 0x0, 0x2)
	github.com/onflow/flow-cli/internal/command/command.go:170 +0x2dd
github.com/spf13/cobra.(*Command).execute(0x5c3d7c0, 0xc00003c080, 0x2, 0x2, 0x5c3d7c0, 0xc00003c080)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c7340, 0xc000387f70, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/onflow/flow-cli/cmd/flow/main.go:65 +0x365

**Comment by sideninja** [comment]
Can you share the `flow.json` file in question?

**Comment by sideninja** [comment]
Fix pending #202

**Comment by bjartek** [comment]
{

	"emulators": {
		"default": {
			"port": 3569,
			"serviceAccount": "emulator-account"
		}
	},
	"contracts": {
		"NonFungibleToken" : "./contracts/NonFungibleToken.cdc",
		"Art" : "./contracts/versus/Art.cdc",
		"Content" : "./contracts/versus/Content.cdc",
		"TopShot" : "./contracts/topshot/TopShot.cdc",
		"FungibleToken": {
			"source": "./contracts/FungibleToken.cdc",
			"aliases": {
				"testnet": "9a0766d93b6608b7",
				"emulator": "ee82856bf20e2aa6"
			}
		}
	},
	"networks": {
		"emulator": {
			"host": "127.0.0.1:3569",
			"chain": "flow-emulator"
		},
		"mainnet": {
			"host": "access.mainnet.nodes.onflow.org:9000",
			"chain": "flow-mainnet"
		},
		"testnet": {
			"host": "access.devnet.nodes.onflow.org:9000",
			"chain": "flow-testnet"
		}
	},
	"accounts": {
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"keys": "b6a7cdbfc20002982a2ed7242583bacab4cd0ca13e6a4898d638abaf005e23a4",
			"chain": "flow-emulator"
		}
	},
	"deployments": {
		"emulator" : {
			"2emulator-account" : [
				"NonFungibleToken",
				"Content",
				"Art",
				"TopShot"
			]
		}
	}
}

**Comment by sideninja** [comment]
I realized the concrete configuration doesn't matter just the fact that configuration is broken by having an account or contract that doesn't exist, is that what you meant?
