### ISSUE TITLE
Report emulator execution errors in cli output

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#22]
### Issue To Be Solved

When using built-in cli commands eg, `flow accounts add-contract`, the cli reports a successful tx submission, but execution can still fail on the emulator. 

### (Optional): Suggest A Solution
The cli should not output anything until the emulator has finished, and any emulator messages, especially errors, should be reported in the cli output.

**Comment by sideninja** [comment]
Solved in #100
