### ISSUE TITLE
encoding/hex: invalid byte: U+0049 'I'

### ISSUE THREAD

**Issue by kulame** [onflow/flow-cli#227]
### Instructions

i try to signed a transcations script, but the flow tell me invalid byte.

### Problem

❌ Command Error: failed to decode partial transaction from ./build.rlp: encoding/hex: invalid byte: U+0049 'I'

### Steps to Reproduce

- ➜  flow flow transactions build trans.cdc --save build.rlp  
💾 result saved to: build.rlp 
 
it's ok

but when i want to signed this rlp script.

➜  flow flow transactions sign ./build.rlp --signer emulator-account --save signed.rlp
❌ Command Error: failed to decode partial transaction from ./build.rlp: encoding/hex: invalid byte: U+0049 'I'

what happened on it?

### Context
➜  flow flow version
Version: v0.18.0
Commit: 980465a86a38f8440375c4949c54930d1019ea14

**Comment by sideninja** [comment]
You should save only payload by using `flow transactions build trans.cdc --fitler payload --save build.rlp` 
I might add a better warning if this happens. Take a look at the documentation https://docs.onflow.org/flow-cli/build-transactions/
