### ISSUE TITLE
Can't get --arg Bool:true to work

### ISSUE THREAD

**Issue by luca-mayven** [onflow/flow-cli#228]
### Problem

I'm trying to pass a Bool argument with flow-cli but it simply doesn't work and it always throws me this error

Command Error: failed to decode value: invalid JSON Cadence structure

I tried with the following options without success

--arg Bool:true 
--arg Bool:"true" 
--arg Bool:1

if I pass it as --args-json it works

--args-json '[{"type": "Bool","value": true}]'

### Steps to Reproduce

try sending any transaction that needs a Bool parameter with --arg

### Acceptance Criteria

I'm able to run "flow transactions send ./transaction.cdc --arg Bool:true"

Thanks!

**Comment by sideninja** [comment]
Good report, fixed with next release.
