### ISSUE TITLE
Add an `accounts list`and other helpful accounts  commands

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#23]
Add a command to list details about accounts you created while using the cli.

### Issue To Be Solved

After an account is created using the cli, there is no way to recall the account address or keys. 
There is no means to introspect accounts in any way without using one of the SDKs.

This would be especially useful for quick debugging in development.

### (Optional): Suggest A Solution

- The cli should provide a command to: 
    - List Addresses and keys for all accounts
    - A means to introspect accounts and get deployed contracts
    - A means to alias account addresses for easier lookup

**Comment by sideninja** [comment]
Implemented in #42
