### ISSUE TITLE
Deploying contract without name

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#231]
Could we remove the name parameter when deploying a contract or at least make it optional since it must match the name of the contract from file which could just be read from the file itself.

**Comment by sideninja** [comment]
Implementation inspiration https://github.com/onflow/flow-playground-api/blob/a5e76a3228e70c9ccfd34b218d7ea91c10292af3/resolver.go#L223

**Comment by bjartek** [comment]
I think the commands to deploy contracts manually and not through `flow project` should just be removed, it is just confusing to have multiple ways to do it. Last I checked they do not resolve imports either.

**Comment by bluesign** [comment]
> I think the commands to deploy contracts manually and not through flow project should just be removed, it is just confusing to have multiple ways to do it. Last I checked they do not resolve imports either.

I think deployed is a bit advanced use. With new contract import syntax ( https://github.com/onflow/flow-cli/issues/502 ) single deploy command, will make much more sense.
