### ISSUE TITLE
Problem with JSON output format

### ISSUE THREAD

**Issue by luca-mayven** [onflow/flow-cli#234]
### Problem

Thanks for fixing the problem about the JSON output option crashing the flow-cli, but now I think we have another problem.

When I try to return an array of struct data, now all the struct is not properly formatted and it's impossible to parse it.
Basically what you're returning now it's not a real JSON anymore.

For example this is what I get when I query for a list of test data

`{"result":"[A.f8d6e0586b0a20c7.Test.TestData(id: 0, name: \"test\", ownerName: \"test\", ownerAddress: 0xf8d6e0586b0a20c7, description: \"test test\", testBool: false, testInt: 3, testFix: 1619615809.00000000)]"}`

### Steps to Reproduce

Try to output any script as JSON and parse it with PHP or any other tool

### Acceptance Criteria

If I'm able to parse the JSON output of the flow-cli

### Context

Using the latest flow-cli released today on macOS

Thanks!!

**Comment by luca-mayven** [comment]
One more thing, same thing happens with events too.

Transactions seems to be fine.

**Comment by luca-mayven** [comment]
And just in case you missed it, the Address field type is not within quotes, so it won't be parsed as string but should be in my opinion

**Comment by psiemens** [comment]
Hey @luca-mayven thanks for reporting! I've confirmed that this is a bug. 

We'll work on a fix and post any updates here 😄

**Comment by luca-mayven** [comment]
Thanks a lot Pete!!

**Comment by luca-mayven** [comment]
Awesome!
Yeah, I think it's totally fine even if it needs to have a bit complex structure, as long as it's a standard JSON that I can parse :)

Thanks a lot!

**Comment by sideninja** [comment]
For simpler values will just be
```
{"type":"String","value":"Hello Meow"}
```
