### ISSUE TITLE
Add NFT to service acct, list SA contract addresses

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#24]
### Issue To Be Solved

It's unclear what contracts are available pre-installed in the emulator. 

### (Optional): Suggest A Solution

Working towards `batteries included` Emulator should come packed with example contracts (TopShot, NFT, Marketplace...etc)
as well as the ability to list out their addresses and any other relevent info in the cli.

**Comment by sideninja** [comment]
Closing this issue as I beleive it's emulator related issue and also the emulator now when ran outputs in the debug all the contract deployed and their addresses.
