### ISSUE TITLE
v0.20.2 artifacts not published - cannot download via install script

### ISSUE THREAD

**Issue by mkarpusiewicz** [onflow/flow-cli#247]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Default instalation method doesn't work:
`sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"`
returns
```
Downloading version v0.20.2 ...
######################################################################## 100.0%
Version v0.20.2 could not be found
```
Checked and https://storage.googleapis.com/flow-cli/flow-x86_64-linux-v0.20.2 is not present.

Seems like the artifact was not pushed to homebrew as well as it doesn't find new version.

However https://storage.googleapis.com/flow-cli/version.txt returns `v0.20.2`

### Steps to Reproduce

See above

### Acceptance Criteria

New version v.0.20.2 can be downloaded. Also it would be nice if the script could work with pinned version. It takes arg[1] param as version but there are no examples in the documentation how to use it with pinned version. Maybe that would be a nice enhancement? like `sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" -- v0.19.0`

### Context

CI pipeline in a project I am working on broke today as it downloads flow-cli for integration tests.

**Comment by sideninja** [comment]
Thank you for the report, please try again

**Comment by mkarpusiewicz** [comment]
Thanks for quick response, it's all fine now ;)
