### ISSUE TITLE
Result optimization

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#249]
### Issue To Be Solved
The results for some commands can be too verbose and hence drown the user with irrelevant or not needed data.

One such example is transaction result with payload value. Payload value is not commonly used but it can take more screen than the percentage of it being used (>50%). 

### (Optional): Suggest A Solution

Introduce hidden fields that can be "expanded" on the request. The result can provide some values that are hidden (just provide the field name) and allow the user to specify the field to be expanded via flag. The flag can be `--include`.

Example:

```
Status          ✅ SEALED
ID              1d806939b326fcb9b0cc1aadc703db77476c285b25ce4dc471e0d535e97749b7
Payer           18eb4ee6b3c026d2
Authorizers     [6a707c4ad375ad50]

Proposal Key:   
    Address     6a707c4ad375ad50
    Index       6
    Sequence    11

Payload Signature 0:
    Address     6a707c4ad375ad50

Payload Signature 1:
    Address     6a707c4ad375ad50

Envelope Signature 0:
    Address     18eb4ee6b3c026d2
   (hidden, use: --include signatures)

Events: (hidden, use: --include events)

Arguments       No arguments

Code (hidden, use: --include code)

Payload (hidden, use: --include payload)
```

Another flag that could be introduced in the same nature is: `--exclude` flag which explicitly removes a field from the result.

**Comment by Kay-Zee** [comment]
Another things re: results, i noticed that the output for updating a contract doesn't provide a tx hash. It's something i try to keep to have an audit trail of what's happening to an account. Shouldn't the tx hash be printed by default? Do i have to specify "debug" to see the tx hash?

**Comment by sideninja** [comment]
> Another things re: results, i noticed that the output for updating a contract doesn't provide a tx hash. It's something i try to keep to have an audit trail of what's happening to an account. Shouldn't the tx hash be printed by default? Do i have to specify "debug" to see the tx hash?

Good catch, I will add hashes to all transaction operations as part of this PR. If you have any other feedback on result please let me know and I will include this with next release.
