### ISSUE TITLE
Add subset of live network state to Emulator

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#25]
### Issue To Be Solved

Some applications will want to build on top of other applications already deployed on Flow. 
This is difficult, given currently there is no way to simulate live network contracts and their state besides manually deploying those contracts on the Emulator, and generating interactions to arrive at the desired starting state.

### (Optional): Suggest A Solution

Ability to load a slice of time/block delineated protocol state (Testnet or Mainnet) into the Emulator using a cli command.

**Comment by psiemens** [comment]
@10thfloor can you move this issue to https://github.com/onflow/emulator?

**Comment by janezpodhostnik** [comment]
Moved to: https://github.com/onflow/flow-emulator/issues/26
