### ISSUE TITLE
Cannot import built-in contracts

### ISSUE THREAD

**Issue by avcdsld** [onflow/flow-cli#252]
### Problem

An error occurs when executing a script that imports a built-in contract (`Crypto` contract) with Flow CLI command.

### Steps to Reproduce

1. Create the following script

test.cdc
```
import Crypto

pub fun main() {
    log("test")
}
```

2. Execute the following command in the Flow CLI of v0.18.0 or later version

```sh
flow scripts execute ./test.cdc
```

The following error occurs
```
❌  Command Error: import Crypto could not be resolved from the configuration
```

### Context

It does not occur with v0.17.0, but with v0.18.0 and later. I am using macOS.
This may be due to `Resolve Contract Imports in Scripts and Transactions` feature.

**Comment by sideninja** [comment]
Thank you for this report. Fix is available in PR #256 and will be included in the next release.
