### ISSUE TITLE
Include complete block results

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#28]
### Issue To Be Solved

Currently the block result printed by the CLI (`flow blocks get`) is only a partial representation of a complete block. For example, it is missing most of the fields from the block header: https://github.com/onflow/flow-go/blob/master/model/flow/header.go#L16-L27

### Suggest A Solution

The CLI should print all block data returned by the Access API. Currently the Access API does not return everything, so it will need to be updated first. After the API is updated, this tool should be updated to print the new data. 

The format of the additional data (e.g. block signers) is TBD, but should be consistent with other CLI commands.

**Comment by sideninja** [comment]
This is the current presentation of block:

Does this include all the data wanted?
```
Block ID		69bf094ced9f1318c2710b224bc40c8541be1b8c0e24f9011f0f9539f5e49089
Parent ID		fd2ebc85655704d382fcfefd4a1445802211b627a2d160c294b1f07489d1c3d4
Timestamp		2021-03-26 11:36:43.417803197 +0000 UTC
Height			13077644
Total Seals		0
Total Collections	3
    Collection 0:	55644f9cef9ef32e9baa329f7a971c1d424788105c1b66bf797db99957437796
         Transaction 0: 6210b35c7c01f04420891d335a327eb8f0668486ca789ced2ef6f51ea4ac1c50
    Collection 1:	d416173af95f2daaf63b52608a52d6f9eece497da337104f19214e4eee76017f
         Transaction 0: 333ad49794eebd11907627536c9407310bdaf64a6b5f0c306d20eabe5275b88b
    Collection 2:	ec3fe970b1455d291a6c686da61a28301c08ffa0d82cafc21ca8d502d3ef12f6
         Transaction 0: 4d49756c3643aa9f11e1137d8a47cc67b7ad223e63c1f3f20beb4458c66fbb95

```
