### ISSUE TITLE
Apple M1 Incompatibility issue with Flow CLI

### ISSUE THREAD

**Issue by DougDimola** [onflow/flow-cli#280]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

When trying to get the latest Flow CLI 0.21.0, I got a compatibility issue with the Apple M1 chip set. 

Error:
unknown CPU type: arm64

### Steps to Reproduce

1) Install the latest Flow CLI on a Apple with an M1 processor. Error spits out immediately upon attempt to install.

### Work Around

Currently can work around this issue  by running the following call in the terminal to run on the Intel instruction set.

arch -x86_64 zsh

**Comment by turbolent** [comment]
@DougDimola Thank you for the report! Could you please provide the error message that you see?

**Comment by DougDimola** [comment]
@turbolent 

Only error print out:
unknown CPU type: arm64
exit

**Comment by sideninja** [comment]
@DougDimola what was your method for installing?

**Comment by DougDimola** [comment]
Script - 

sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

**Comment by sideninja** [comment]
You would need to use brew to install CLI on M1, as it is described in docs method you used only works for x86-64.
https://docs.onflow.org/flow-cli/install
