### ISSUE TITLE
Cannot send a transaction with multiple signers using Flow CLI

### ISSUE THREAD

**Issue by codewolf82** [onflow/flow-cli#283]
Creating issue from response to my forum post here: https://forum.onflow.org/t/how-to-send-transaction-with-multiple-signers-using-flow-cli/2023

Given a cadence transaction script, which accepts multiple AuthAccount arguments; it is not possible to send a transaction with more than a single signer using Flow CLI.

Docs indicate arg accepts a String: 
```
--signer string      Account name from configuration used to sign the transaction (default "emulator-account")
```

Only a single `--signer` argument can be sent.

### Steps to Reproduce

Create a simple transaction script that accepts two AuthAccount args

```
transaction {
   prepare(acc1: AuthAccount, acc2: AuthAccount) {
      ...
   }
}
```

Use Flow CLI to invoke the transaction: 

Multiple signer args: `flow transactions send ./trans.cdc --signer acc1 --signer acc2`

```
WARN[0441] ERR [a81811] [Error Code: 1101] cadence runtime error Execution failed:
error: authorizer count mismatch for transaction: expected 2, got 1
```

Comma delimited signers: `flow transactions send ./trans.cdc --signer acc1,acc2`

```
Command Error: signer account: [acc1,acc2] doesn't exists in configuration
```

Space delimited signers: `flow transactions send ./trans.cdc --signer acc1,acc2`

```
accepts at most 1 arg(s), received 2
```

From asking on the the forum, I think this is the script in question: https://github.com/onflow/flow-cli/blob/1d45016b6a5d0abeba3ac91b88f342f5b850c145/internal/transactions/sign.go

### Expected behaviour

Allowed to send multiple signers to a transaction script via CLI; this behaviour works fine in Flow Playground and using the JS SDK.

### Environment

MacOS (Big Sur)
Flow CLI version v0.21.0

Ubuntu 20.04 (running in Docker)
Flow CLI version v0.21.0

**Comment by sideninja** [comment]
answered on forum:

> Thanks for flagging this, we might add support for signing with multiple signers using the send command, but meanwhile, you can achieve the same by using build and send signed commands. Please check the documentation about it here: Build a Transaction with the Flow CLI - Flow Documentation

You would build a transaction and specify multiple authorizers by doing flow build ./tx.cdc --authorizer 0x1 --authorizer 0x2 ... (follow the docs), next you would sign using flow sign and after that you would use the flow send-signed command to broadcast the signed transaction.
