### ISSUE TITLE
install.sh is currently returning an error when executed without arguments

### ISSUE THREAD

**Issue by briandilley** [onflow/flow-cli#305]
when installing the flow-cli using the documented script:

`   sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"`

the following error is reported and nothing is installed:

` Version v0.24.1 could not be found`

**Comment by comtechnet** [comment]
Yes - and similarly - the Windows X  flow-cli install/update command fails with a similar/same error 

![image](https://user-images.githubusercontent.com/5374172/123283897-cd29ea00-d4d9-11eb-8499-fe5f6d0bc833.png)

**Comment by turbolent** [comment]
@briandilley @comtechnet Thank you for the report!

[v0.25.0 is out now](https://github.com/onflow/flow-cli/releases/tag/v0.25.0), and I just uploaded the binaries (I checked https://storage.googleapis.com/flow-cli/). 

Could you please try updating to v0.25.0 and see if that works for you? Thanks!

**Comment by comtechnet** [comment]
v0.25.0 "upgrade step" DOES INDEED WORK now - yes; However - when a "user" simply follows the instructions to perform the FLOW CLI upgrade - running the instructions as directed/provided - FIXES the update - but the command flow status results in:

Config Error: invalid key type for account testnet-account

When the immediate early verfsion had not problem with flow status

I'm guessing that there is a pre-req likely annouced/provided of an earlier change to the setup.  I did see some changes that claim to "break" the setup - will check my config

**Comment by turbolent** [comment]
@comtechnet Thank you for verifying the update could be installed. 

As for the other problem, could you please open a separate issue in case this is broken? Thanks!

**Comment by comtechnet** [comment]
Looks like a VSCode issue - fixed - had to restart VSCode - all good now!  Thanks

**Comment by comtechnet** [comment]
I'm using WSL2 - gets a little wonky at times - but I love it!
