### ISSUE TITLE
Doc on CLI configurations is not correct (I believe) - regarding alias account information on using the emulator

### ISSUE THREAD

**Issue by comtechnet** [onflow/flow-cli#309]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

I believe the following text needs corrected.

Advanced Format
Using advanced format we can define aliases. Aliases define an address where the contract is already deployed for that specific network. In the example scenario below the contract FungibleToken would be imported from the address 9a0766d93b6608b7 when deploying to testnet network and address ee82856bf20e2aa6 when deploying to testnet. We can specify aliases for each network we have defined. When deploying to testnet it is always a good idea to specify aliases for all the common contracts that have already been deployed to the testnet.

### Steps to Reproduce

View the URL:  https://docs.onflow.org/flow-cli/configuration/

### Acceptance Criteria

Fix the instructions to read:

Advanced Format
Using advanced format we can define aliases. Aliases define an address where the contract is already deployed for that specific network. In the example scenario below the contract FungibleToken would be imported from the address 9a0766d93b6608b7 when deploying to testnet network and address ee82856bf20e2aa6 when deploying to the Flow emulator. We can specify aliases for each network we have defined. When deploying to testnet it is always a good idea to specify aliases for all the common contracts that have already been deployed to the testnet.

### Context

Learning Flow

**Comment by sideninja** [comment]
Thank you, will fix it.
