### ISSUE TITLE
Refactor flow events get to use flags for blocks

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#324]
### Instructions

`flow events get` uses arguments for blocks and event names, switching to flags for blocks would make it easier to submit more events and would make it possible to have more semantic meaning flags. 

 

### Problem

in #315 there was introduced specifying -10 as an argument that would mean fetch latest blocks. However cobra behaves strangely when using `-` in arguments so you need to terminate the flag processor with --. This is not ideal.

### Acceptance Criteria

Suggested flags are:
 --start <int> start block as a int
 --end  <int> end block as an int
 --last <int> fetches that last x blocks relative to related height.

As for #319 it could need the following flags
 --workers/-w <int> how many workers to use as default (10, not sure this is the correct default value here?)
 --batches/-b <int> how large a batch of blocks to send to a worker (250) this default should be synced with gateway limit

### Context

Just helping out making the CLI a good place to be.

**Comment by bjartek** [comment]
Question:
 - What should be the default values when not specifying any flags here? Personally I would go with just fetch for the last block, that is --last 1

**Comment by bjartek** [comment]
I took a stab at fixing this in #319

**Comment by sideninja** [comment]
I would personally require either `--last` flag or combination of `--start --end`. I'm afraid that running the command without any arguments: `flow events get flow.Event` would imply you are getting all the arguments, so I prefer being explicit about the values.

**Comment by bjartek** [comment]
Ok fine by me.

**Comment by bjartek** [comment]
I think fetching the events from some of the latest blocks makes sense. I would normally run it to fetch events that my last transaction would emit, so using an internal that would exceed normal seal block time would be preferable. What about 10?

Using required flags is as you have stated against your own guidelines. And I think that as long as the docs is clear people would not exect to fetch all events.

**Comment by sideninja** [comment]
I understand, maybe having a smaller interval is more resourceful and covers the majority of the cases. But like you said it needs to be documented. I believe this is quite subjective and I don't feel I have a strong argument for any of them so I can agree with yours.
