### ISSUE TITLE
Make it possible to output emulator log when using Emulator gateway

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#325]
## Instructions

When using the emulator gateway sometimes it is desired to actually see the log. Currently i find no way of doing this, it would be nice if there was an option for this.

### Issue To Be Solved

Go-with-the-flow is beeing rewritten untop of the improvements in flowkit and it would be very nice to be able to see the log of the emulator weaved into the ouput log of the tool.

### (Optional): Context

This is the branch of go-with-the-flow that has the new draft code https://github.com/bjartek/go-with-the-flow/tree/main

`cd examples && go run demo/main.go` will print out the log messages from go-with-the-flow but not from the emulator

**Comment by sideninja** [comment]
I'm not sure if you know this but flowkit can be run using "embedded" emulator instance, as seen in [integration testing](https://github.com/onflow/flow-cli/blob/master/pkg/flowkit/services/accounts_test.go#L249).

The emulator implementation could be changed to using [backend](https://github.com/onflow/flow-emulator/blob/142a19ebc6a704501ec10becbc5fbc416f9f4c04/server/backend/backend.go#L51) and you could inject your own logger instance, or the current implementation could be extended with logger and you could again pass your own logger.

Implementing the backend instead of the emulator would clean up some of the code in CLI.

**Comment by bjartek** [comment]
The technique you mention in integration testing is what i do today.

The backend solution is what I want I think but not really sure. How do i create services when I have a backend?

**Comment by bjartek** [comment]
The technique you mention in integration testing is what i do today.

The backend solution is what I want I think but not really sure. How do i create services when I have a backend?

**Comment by sideninja** [comment]
> The technique you mention in integration testing is what I do today.
> 
> The backend solution is what I want I think but not really sure. How do I create services when I have a backend?

You currently can't, a refactor would be needed for that, it wouldn't be a hard one tho, just passing the emulator instance to the backend and making sure all the exposed methods are complying with the interface.

**Comment by bjartek** [comment]
I am afraid I do not even know where to start on this one. But I would really love to have the feature. Also the logging from emulator with colors and all would look dandy cool in the cli.

**Comment by sideninja** [comment]
I will implement this as part of the effort to improve the vscode extension. Language server required by vscode extension will be refactored so it will manage the emulator by using flowkit with the hosted gateway, but I will need to provide logs to the extension itself so I will implement a logging feature for hosted gateway you can then reuse in your implementation.

**Comment by bjartek** [comment]
Status update?

**Comment by sideninja** [comment]
The work on the vscode still hasn't started, we are trying to get more people to address this and hopefully, this will happen soon. But you can solve that for yourself right now, you just need to change the implementation to not [use blockchain](https://github.com/onflow/flow-cli/blob/master/pkg/flowkit/gateway/emulator.go#L37) but [use backend](https://github.com/onflow/flow-emulator/blob/3da55fa9545e39b7a2a7587b9923e83919626e3a/server/backend/backend.go#L44) and pass it your own logger, see backend definition

**Comment by bjartek** [comment]
I tried to use backend instead of blockchain but Services requires Gateway and Backend does not implement `ExecuteScript`

../overflow/setup.go:196:34: cannot use gw (variable of type *backend.Backend) as type gateway.Gateway in argument to services.NewServices:
	*backend.Backend does not implement gateway.Gateway (missing ExecuteScript method)

**Comment by sideninja** [comment]
> I tried to use backend instead of blockchain but Services requires Gateway and Backend does not implement `ExecuteScript`
> 
> ../overflow/setup.go:196:34: cannot use gw (variable of type *backend.Backend) as type gateway.Gateway in argument to services.NewServices: *backend.Backend does not implement gateway.Gateway (missing ExecuteScript method)

umm? not sure if I understand how is that related.

**Comment by sideninja** [comment]
oh sorry, I thought this comment was under FLIP. 

What is this backend implementation? I'm not sure which implementation is that? 

Also about the log, I know it's been long and it's not yet addressed but the current plan is that when I work on LS improvements I will implement this logging as I will also need it to be streamed to clients.

**Comment by bjartek** [comment]
The backed is this https://github.com/onflow/flow-emulator/blob/3da55fa9545e39b7a2a7587b9923e83919626e3a/server/backend/backend.go#L44 that you linked above. 

Do you have an eta?

**Comment by sideninja** [comment]
I see yeah. Well, these are two different problems to some extent. So the last problem with not implementing the interface a quick workaround would be to just add that method but it doesn't have anything in the body, the correct solution would be adding the implementation. I will take a look at that but currently, I have other priority work so you are welcome to do so if you don't want to wait. It's hard for me to give you ETAs as I have my hands pretty full but I'm excited about team expansion that is going on so this things will be addressed quicker in the near future 🙏
