### ISSUE TITLE
Support sending in multiple signers in the send method

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#326]
## Instructions

In go-with-the-flow I create a DSL to send transactions and sometimes I want to sign this using multiple signers. I would like to support this without having to rewrite the Send method and serialize to byte[] and back to use Build/Sign/Sign/SendSigned.

### Issue To Be Solved

Sign with multiple singers without having to rewrite part of the code

(Replace this text:
Please present a concise description of the problem to be addressed by this feature request.
Please be clear what parts of the problem are considered to be in-scope and out-of-scope.)

### (Optional): Suggest A Solution

Change the signature from
```
func (t *Transactions) Send(
	signer *flowkit.Account,
	code []byte,
	codeFilename string,
	gasLimit uint64,
	args []cadence.Value,
	network string,
) (*flow.Transaction, *flow.TransactionResult, error) {
```

to
```
func (t *Transactions) Send(
	signer *flowkit.Account,
	code []byte,
	codeFilename string,
	gasLimit uint64,
	args []cadence.Value,
	network string,
	payloadSigners []*flowKit.Account
) (*flow.Transaction, *flow.TransactionResult, error) {
```

iterate over payloadSigners and sign with them in the method

**Comment by sideninja** [comment]
Why couldn't this just be implemented using the `signer` argument as an array and passing multiple signers?

**Comment by bjartek** [comment]
It could be an array but how do you then decide who is payer and proposer? 

We could just use the first entry for that. That would work for me.

**Comment by sideninja** [comment]
Do you need to pass additional authorizers of the transaction?

**Comment by bjartek** [comment]
I think so. https://github.com/bjartek/go-with-the-flow/blob/master/gwtf/perform.go this is the code i have before the refactor.

The examples folder has a transaction with 2 authaccounts in a transaction. That is what i want to do here.

**Comment by sideninja** [comment]
Yes, that is the case. Signer was used so far in the send transactions command to fulfill the role of proposer, payer, and authorizer. To be honest, I think it would be more correct for the send command to have `proposer`, `authorizer` and `payer` flags the same way as the build does, but since sending the transaction is usually done with the same proposer, authorizer, and payer the flag signer covers all three and it is more practical to stay this way.

I wouldn't change the commands flags and arguments but maybe we can change the send function in the flowkit to accept proposer, payer, and authorizers as that is more correct and it doesn't change the usage of the CLI.

**Comment by bjartek** [comment]
Sounds like a plan

**Comment by sideninja** [comment]
But then again what if you would use `Build` function with sdk send like so:
```
tx, err := services.Build(
		signer.Address(), // proposer
		[]flow.Address{signer.Address()}, // authorizers
		signer.Address(), // payer
		signerKeyIndex,
		code,
		codeFilename,
		gasLimit,
		args,
		network,
	)
	if err != nil {
		return nil, nil, err
	}

	err = tx.SetSigner(signer)
	if err != nil {
		return nil, nil, err
	}

	signed, err := tx.Sign()
	if err != nil {
		return nil, nil, err
	}

	sentTx, err := t.gateway.SendSignedTransaction(signed)
	if err != nil {
		return nil, nil, err
	}
```

This way you are still leveraging the work of the flowkit but not changing the API of Send function.

Sorry, but I'm being hesitant about changing the Send function to tailor to this case which I think might be less common.

**Comment by bjartek** [comment]
Let me try if that code works :)

**Comment by sideninja** [comment]
> Let me try if that code works :)

For the last one you can even use the `transactions.SendSigned` and just pass `tx.FlowTransaction().PayloadMessage()`

**Comment by bjartek** [comment]
I tried using the Build method as you suggested but it does not manage to decode my transaction: 
https://github.com/bjartek/go-with-the-flow/tree/multisign

NB! Note that go.mod points to my local copy of flow-cli that is my flow-cli branch.

**Comment by bjartek** [comment]
I have played around with this a bit more and this works

```
tx, err := t.GoWithTheFlow.Services.Transactions.Build(
		t.MainSigner.Address(),
		authorizers,
		t.MainSigner.Address(),
		signerKeyIndex,
		code,
		codeFileName,
		t.GasLimit,
		t.Arguments,
		t.GoWithTheFlow.Network,
	)
	if err != nil {
		log.Fatal(err)
	}

	for _, signer := range signers{
		err = tx.SetSigner(signer)
		if err != nil {
			log.Fatal(err)
		}

		tx, err = tx.Sign()
		if err != nil {
			log.Fatal(err)
		}
	}


	txBytes :=[]byte(fmt.Sprintf("%x", tx.FlowTransaction().Encode()))
	_, res, err := t.GoWithTheFlow.Services.Transactions.SendSigned(txBytes)
```

**Comment by sideninja** [comment]
> I have played around with this a bit more and this works
> 
> ```
> tx, err := t.GoWithTheFlow.Services.Transactions.Build(
> 		t.MainSigner.Address(),
> 		authorizers,
> 		t.MainSigner.Address(),
> 		signerKeyIndex,
> 		code,
> 		codeFileName,
> 		t.GasLimit,
> 		t.Arguments,
> 		t.GoWithTheFlow.Network,
> 	)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	for _, signer := range signers{
> 		err = tx.SetSigner(signer)
> 		if err != nil {
> 			log.Fatal(err)
> 		}
> 
> 		tx, err = tx.Sign()
> 		if err != nil {
> 			log.Fatal(err)
> 		}
> 	}
> 
> 
> 	txBytes :=[]byte(fmt.Sprintf("%x", tx.FlowTransaction().Encode()))
> 	_, res, err := t.GoWithTheFlow.Services.Transactions.SendSigned(txBytes)
> ```

We could potentially add a helper method for this encoding to the FlowTransaction. I'm glad it works.

**Comment by bjartek** [comment]
What would this helper method be called? I belive putting in on flowkit.Transaction would be a good idea?

EncodeRLP?

**Comment by sideninja** [comment]
Yes, that is ok, but I'm wondering why just using: `services.Transactions.SendSigned(tx.FlowTransaction().Encode())` wouldn't work. I will try to figure out why is this weird conversion needed.

**Comment by bjartek** [comment]
This issue is not relevant anymore and it can be closed.
