### ISSUE TITLE
Better contract deployment support - Multiple transaction authorizers

### ISSUE THREAD

**Issue by tehranifar** [onflow/flow-cli#329]
### Issue To Be Solved

Deploying a contract is time-consuming at the moment. We think we can do better by adding multiple authorizer support to the CLI.

### (Optional): Suggest A Solution

We’d need to support multiple `--authorizer` flags, for example `--authorizer alice --authorizer bob`

**Comment by tehranifar** [comment]
I can make a PR to add support for the above

**Comment by sideninja** [comment]
Can you describe the current process needed for partner contract deployment?
How exactly would the auto-top-up feature work? Where it would take the funds from? How it would calculate required funds?

**Comment by tehranifar** [comment]
> Can you describe the current process needed for partner contract deployment so I can better understand the problem behind this?

As far as I know, partner contract deployments require us to add two full weight keys on the account (one we control and another the partner controls) + adding the necessary FLOW tokens to store the contract code. @psiemens can elaborate more if I missed a step here.

> How exactly would the auto-top-up feature work? Where it would take the funds from? How it would calculate the required funds?

The tokens are taken from the payer account that creates the contract (as expected) and I think it's the intended behavior for us. On Dapper we calculated the required amount based on the contract code byte size offchain:
```go
// add extra FLOW tokens for code storage
cadenceExtraFlowTokens, err := cadence.NewUFix64(
	fmt.Sprintf("%f", float64(len(accountCode))/StoragePerFlowTokenInBytes))
if err != nil {
	return nil, err
}
```
Added an extra argument to deploy contract transaction:
```swift
import FungibleToken from {{.FungibleToken}}
import FlowToken from {{.FlowToken}}

transaction(publicKeys: [String], contracts: {String: String}, extraFlowBalance: UFix64) {
	prepare(signer: AuthAccount) {
		let acct = AuthAccount(payer: signer)

		for key in publicKeys {
			acct.addPublicKey(key.decodeHex())
		}

		for contract in contracts.keys {
			acct.contracts.add(name: contract, code: contracts[contract]!.decodeHex())
		}

	   	let vaultRef = signer.borrow<&FlowToken.Vault>(from: /storage/flowTokenVault)
			?? panic("Could not borrow reference to the owner's FlowToken Vault!")

		let receiverRef = acct.getCapability(/public/flowTokenReceiver)!.borrow<&{FungibleToken.Receiver}>()
			?? panic("Could not borrow receiver reference to the new account's FlowToken Vault")

		receiverRef.deposit(from: <- vaultRef.withdraw(amount: extraFlowBalance))
	}
}
```

> The need for "extra authorizers" or signers is valid and has been raised for other commands (send transactions), but I would be careful about naming and consistency. I think that just providing --authorizer flag multiple times would be more consistent the same way as it is used in the build transaction command.

Thanks for the suggestion. I agree with the above.

**Comment by sideninja** [comment]
Thank you for the write up, how critical do you think this is (timewise)? 

I like the idea for a feature that would send an amount of Flow needed for deployment to succeed, I think this even might be the default behaviour, will think more about it and update. The fact the tokens would be taken from the payer is logical 👍 

The multiple authorizers for a contract deployment would require a go-SDK change for the template to support the multiple authorizers, but I think it can be done, however, I would divide and conquer these two tasks as separate PRs.

**Comment by tehranifar** [comment]
> how critical do you think this is (timewise)?

Peter is handling contract deployments manually and we have quite a lot of them each week. We were planning to add these features to the CLI to save time on contract deployments and reduce the steps needed per each deployment. 

I can implement the needed changes when you are confident enough on the exact specification (you mentioned you'll think more about it).

**Comment by sideninja** [comment]
I understand. If you can implement these features that would be great.

I would keep authorizer flags consistent with build command so in case you want to add another authorizer you specify them as `--authorizer alice` or multiple `--authorizer alice --authorizer bob`.

Regarding the `auto-top-up` flag, I believe the CLI should automatically send as many funds as needed for the contract to be deployed successfully, what do you think? 
I don't see a benefit of preparing the transaction in the CLI which will fail due to insufficient funds. One could argue we should notify the user of the transaction costs tho, and I kinda think the same but at the second thought, I don't want to introduce a confirmation screen in this process as this will mean we have to introduce the confirmation screen on all transactions, which again might be a good idea but should be thought out more and we can maybe start without it and add it if users will be flagging it. Maybe we should eventually add the calculation as a separate command so a user can calculate the cost of the transaction by running the command.

I think this should be implemented as two separate features, one to support multiple authorizers and one to change the calculation of the amount sent for transactions?

**Comment by psiemens** [comment]
> I would keep authorizer flags consistent with build command so in case you want to add another authorizer you specify them as --authorizer alice or multiple --authorizer alice --authorizer bob.

I like this better, too!

**Comment by psiemens** [comment]
@tehranifar Since default storage is being increased by a factor of 10, can you adjust the scope of this issue to just be the additional authorizer? @sideninja suggested creating a separate issue for the auto top-up feature, which I think makes sense.

**Comment by tehranifar** [comment]
Issue updated!

**Comment by bjartek** [comment]
How will this work the `flow project deploy`? I often find myself wanting to send a AuthAccount to the init method of a contract and I would like to be able to do that using the `Services.Project.Deploy` feature of flowkit in adition to `flow contract`

**Comment by sideninja** [comment]
@bjartek are you suggesting project deploy functionality should also support signing with multiple authorizers? The term "payload signers" is quite vague since there are different roles under which an actor signs a transaction.

**Comment by bjartek** [comment]
@sideninja the core need here is to able to send an authAccount to init of a contract from `flow project deploy`. If it is possible to do it using flow cli in some other way that is a workaround I would like to know, but I would prefer to use the deploy command.

**Comment by psiemens** [comment]
> How will this work the flow project deploy? I often find myself wanting to send a AuthAccount to the init method of a contract and I would like to be able to do that using the Services.Project.Deploy feature of flowkit in adition to flow contract

I agree that we should support this, but I think it's a separate issue. 

There is no longer a strong need for this particular feature, so I'm going to close this issue.
