### ISSUE TITLE
Grepable output

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#33]
### Issue To Be Solved

It may be worthwhile to restructure our current command output so that it can be easily parsed by tools such as `grep`, `awk`, `diff`, etc. 

Related: https://nmap.org/book/output-formats-grepable-output.html

### Questions

Should "grepable" output be the default, or should we prioritize a human readable format? Is it possible for both to be the same? If not, does it make sense to have grepable output as an option, give that we will likely add JSON output?

**Comment by bjartek** [comment]
I would prefer the default output to be human readable, also I think it is possible to detect if stdOut is a pipe or redirect or not but I am not 100% sure on that.

**Comment by sideninja** [comment]
Solved in #100
