### ISSUE TITLE
Import contract using name

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#332]
## Instructions

Right now it is possible to write

import NonFungibleToken from ":/contract/NonFungibleToken.cdc"

I would like to write
import NonFungibleToken

All the information to support this is in the flow json file. If you combine contracts with deployment and accounts this can be resolved. 

### Issue To Be Solved

Beeing able to import a contract without having to use a specific directory struxture in each implementation file

**Comment by sideninja** [comment]
The reason we are specifying a file is for any IDE to know where to look for the contract and provide code completions etc. You could argue the editor could import a flow.json too (and in our case, it uses it already), but I think it might be more scalable for other implementations to specify import path. 

Another reason is security, I think it's better to be as explicit as possible with what you are importing, if the actual resolution happens "behind the screen" it could lead to an unexpected behaviour.

**Comment by bjartek** [comment]
Good points. Feel free to close this issue then.
