### ISSUE TITLE
Adding a new contract to a local flow.json will copy state from flow.json in home folder

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#335]
### Instructions

Have a flow.json in your home folder. 

Create a new directory and run  `flow init` in it. 
Observe that the empty flow json is created
run `touch foo && flow config add contracts --name foo --filename foo` 
observe that the flow json has the new contract and all the state from the global flow json in it.

**Comment by bjartek** [comment]
If you add -f flow.json to the above flow config parameter then the output will be as expected.

**Comment by bjartek** [comment]
So maybe just mention that in the docs is the proper way to go here.

**Comment by bjartek** [comment]
I am not sure having $HOME/flow.json in defaults paths make much sense. Atleast for these kind of config changing commands it is more of a hassle then a feature.

**Comment by sideninja** [comment]
Having a global flow.json is a feature we believe is useful, however, the behaviour described above is indeed not intuitive and I agree it should be changed. The behaviour should be that the contract gets added to the local flow.json if present. I think that we could change the config loading behaviour to be as follows: first try and load local flow.json if not found only then go and load global flow.json.

**Comment by bjartek** [comment]
That make sense
