### ISSUE TITLE
Secure key storage

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#34]
### Issue To Be Solved

Private keys are currently stored as plaintext fields in `flow.json` 👎 👎 

While we have support for external signing solutions (e.g. Google KMS), we should still make it more secure to sign locally with the CLI. For example, it's common for developers to use the CLI to interact with testnet.

We should explore options to store private keys securely outside of `flow.json`.

### Suggest A Solution

Ideas that come to mind:
- Add option to load private key from environment variable
- Add option to store private key in local OS keychain (is this possible?)
- Add option to store private key in separate file

**Comment by 10thfloor** [comment]
What about something like https://ssh-vault.com/ / https://github.com/ssh-vault/ssh-vault
Crazy?

**Comment by 10thfloor** [comment]
Found a 'bash script' version of the same idea: 
https://github.com/S2-/sshenc.sh

**Comment by bjartek** [comment]
Is this really needed after we add support for keys as envvars or a sepearte private flow json file?

**Comment by sideninja** [comment]
I don't think so. @psiemens since you opened this issue, does private config files and env variables solve all you had in mind opening this?

**Comment by sideninja** [comment]
Solved in #101 #82 #82 and #100
