### ISSUE TITLE
Script errors not reported properly when using gateway.NewEmulatorGateway

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#345]
### Instructions

In go with the flow when I run a script that contains an error it is not reported properly by the EmulatorGateway, however if I use a GrpcGateway against a live running emulator locally it works fine.

### Problem

See test here: https://github.com/bjartek/go-with-the-flow/blob/script-reporting/examples/script_integration_test.go#L32

**Comment by sideninja** [comment]
Thank you for reporting this. I remember I had a similar issue with the emulator not returning an error on script execution, that has been solved but I guess it wasn't solved for running the emulator within the same process. It looks like it's an issue in the CLI gateway emulator implementation.
