### ISSUE TITLE
Getter methods ByName() for contracts, accounts, networks does not return error in config package

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#349]
### Instructions

pkg/flowkit/config there are getters for getting configured contracts, networks, accounts. These return an empty pointer if they are not found. It is tempting to then chain together method calls. However if you have then misconfigured things you will get not so nice error messages. 

Should we fix this so that these return error as seond argument?

**Comment by bjartek** [comment]
On a more thorough look it looks like there are a lot more accessors here that does not return error. Is it worth it do change it at this point?

**Comment by sideninja** [comment]
I think it is worth doing the refactor as it follows idiomatic Go programming and will avoid weird bugs in the future. I however don't see it as the highest priority but if you want to take a stab at it, please do.

**Comment by bjartek** [comment]
I will take a stab at it then. Coding in the evenings and delivering value is soothing right now :)
