### ISSUE TITLE
Cannot supply boolean as initialization argument for contract

### ISSUE THREAD

**Issue by allenoooo** [onflow/flow-cli#351]
### Problem
Cannot supply boolean value as initialization argument for contract via flow-cli

### Steps to Reproduce

Create a contract that takes a boolean value argument into its constructor (init function), and put that arg into a `flow.json` as either a string value "true" or "false", or a naked bool value true or false. The cli will throw an error either way.

### Acceptance Criteria

n/a

### Context

nothing of consequence, and numerous workarounds are available.

### example
```
    "deployments": {
    "emulator": {
      "one": [{
          "name": "Emit",
          "args": [
            {"type": "String", "value": "test"},
            {"type": "Bool", "value": true}
          ]
```
results in: 

```
❯ flow emulator --persist -v
json: cannot unmarshal bool into Go struct field jsonConfig.deployments of type string
```

and:
```
    "deployments": {
    "emulator": {
      "one": [{
          "name": "Emit",
          "args": [
            {"type": "String", "value": "test"},
            {"type": "Bool", "value": "true"}
          ]
```

results in:

```
❯ flow emulator --persist -v
failed to decode value: invalid JSON Cadence structure
```

**Comment by sideninja** [comment]
Thank you for reporting this, this is a bug and should be fixed. Can you just confirm you are using the latest CLI version?

**Comment by allenoooo** [comment]
V0.26 and the latest master commit. Sorry I didn’t include this in the original report.

**Comment by sideninja** [comment]
Thank you, the issue reported is validated and we will try to push an update as soon as we can, hopefully with the next release. If you are keen you can also try and make a PR, community contributions are always welcome.
