### ISSUE TITLE
Testnet faucet integration

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#37]
### Issue To Be Solved

Just an idea at this point, but it'd be convenient if the CLI integrated directly with the [Testnet Faucet](https://testnet-faucet.onflow.org/).

For example:

```
flow testnet-faucet "Peter Siemens" "foo@bar.com"

**Comment by psiemens** [comment]
Maybe we could replace the current email verification with a CAPTCHA challenge? 

That would allow for an authentication flow like this:

- User requests testnet account through CLI
- CLI generates a key pair
- CLI opens faucet page in browser with public key as URL parameter
- User solves CAPTCHA challenge (e.g. [Google reCAPTCHA](https://www.google.com/recaptcha/about/))
- Faucet creates a new account, returns address to browser
- Browser sends address (either via POST or redirect) to a temporary local server being run by the CLI
- CLI receives address, saves to flow.json and displays to user

**Comment by 10thfloor** [comment]
Idea: Auth directly from the cli (without popping up the faucet site) and provide a command like
```
flow testnet-faucet --amount=100.0 --acct=0x12332984
```

**Comment by 10thfloor** [comment]
This could of course be restricted by the underlying API, where we could limit the amout of tokens any 'account' can mint for itself ...etc.

**Comment by bjartek** [comment]
Do you really need to run the local server? Having to do that opens up so many problems IMHO. What if you when you create a new account send in a key and later on you can check the status with that key? I guess you would need to fix the faucet then to support that.

**Comment by sideninja** [comment]
Is this still active and wanted now with the new faucet and captcha? @psiemens
