### ISSUE TITLE
Gas Limit Error When Deploying To Testnet

### ISSUE THREAD

**Issue by samwise2** [onflow/flow-cli#373]
### Problem

Unable to deploy contracts to testnet using flow-cli. Tried on both v0.27 and v0.28.

### Steps to Reproduce

To Reproduce:

1. ` flow project init `
2. Add any contract to ` cadence/contracts ` i.e. ` FungibleToken `
3. ` flow project deploy --network=testnet ` (the same exact error is found when using  `flow accounts add-contract`)

I ran into the following error when deploying various kinds of contracts. Others in the flow discord are experiencing this as well. https://discord.com/channels/613813861610684416/621847426201944074/881410515061075999 

(In this case I used a simple contract called Demo, but the same is observed with any contract).
<img width="1116" alt="Screen Shot 2021-08-29 at 2 10 20 PM" src="https://user-images.githubusercontent.com/24325294/131260952-8840087c-6c90-4f8a-95c5-c520c7d62c78.png">

The deployment account that I'm using was generated from Faucet and should have 1,000 Flow Tokens.

### Acceptance Criteria

Able to deploy contracts to testnet :)

### Context

Working on developing a simple UI for a flow project and I want to work with testnet to integrate with Wallet Providers.

**Comment by luca-mayven** [comment]
I can confirm that the same thing happens to me. Can't create new account and can't deploy contracts on testnet.

**Comment by newbdez33** [comment]
`$ flow accounts create --network testnet --signer testnet-account --key 9d3d48ae994dc34681f3e805d48928c5da3c8985c592a243b8e84e42fa1d4a5ab3d3e21132964a32da8c9665bf2c46854a21b76eddc577b423ec58b80ab229a0
Transaction ID: e0f3b203ec8711b8162aec912d851fe2eab108c97cd7f26988b1df42ae4f7ab0
❌ Invalid argument: invalid transaction: transaction gas limit (0) is not in the acceptable range (min: 1, max: 9999)
🙏 Check your argument and flags value, you can use --help.`

I got the same.

**Comment by sideninja** [comment]
Thank you for reporting, update will be available shortly.
