### ISSUE TITLE
Gas estimation tool

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#38]
### Issue To Be Solved

Currently there's no easy way to estimate the gas consumption from a transaction. Developers can adjust the gas limit on the emulator and perform a manual search, but this is tedious. 

Can the CLI provide a way to automatically estimate the gas used by a transaction? This likely requires integration with other components (Cadence and/or emulator).

**Comment by uhbif19** [comment]
@psiemens Is there any documentation on how gas works available? I have not found anything except mention that transactions are free for now https://docs.onflow.org/faq/developers#how-much-will-gas-cost-on-flow.
