### ISSUE TITLE
Documentation For Transactions With Multiple Signers

### ISSUE THREAD

**Issue by samwise2** [onflow/flow-cli#383]
### Issue To Be Solved

I've spent a lot of time trying to find some guidance on how to sign transactions that require multiple signers using the CLI. There are also many people requesting this in the Flow Discord. The closest thing I can find to an example is in this [external repository](https://github.com/tatumio/flow-contracts#testnet-tests) which provides the following example:

```
flow transactions build ./cadence/transactions/add_minter.cdc --arg "String:TEST_TOKEN_1" --authorizer deployer --authorizer minter --proposer deployer --payer minter -n testnet --filter payload --save built.rlp
flow transactions sign ./built.rlp --signer deployer -n testnet --filter payload --save signed.rlp
flow transactions sign ./signed.rlp --signer deployer -n testnet --filter payload --save signed.rlp
flow transactions sign ./signed.rlp --signer minter -n testnet --filter payload --save signed.rlp
flow transactions send-signed ./signed.rlp -n testnet
```

However, this seems strange because we are signing the transaction twice with the same account. After playing around with the CLI, I believe that this is because there is some sort of loss of information when repeatedly signing this way. I.e. earlier signatures seem to be lost after re-signing the payload later on. However, this is just from some experimental testing, I'm not sure.

In any event, it seems unclear how to do this, andI've been unsuccessful using a similar approach to that above.

### (Optional): Suggest A Solution

Some documentation on signing transactions with multiple signers would be great! Either within the existing docs, or as a separate example.

**Comment by sideninja** [comment]
@samwise2 thank you for reporting this, we will revisit the docs and make sure there are more examples on how to do building/signing of transactions. Meanwhile, if you want assistance with your case ping me on discord, I have the same handle as here
