### ISSUE TITLE
`flow keys generate` fails if run in dir with invalid `flow.json`

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#384]
### Problem

The command `flow keys generate` fails if run in a directory containing an invalid `flow.json` file. 

### Steps to Reproduce

Run `flow keys generate` in a directory containing an invalid `flow.json` file.

### Acceptance Criteria

`flow keys generate` should generate a set of Flow keys, regardless of `flow.json`

**Comment by sideninja** [comment]
What does your `flow.json` looks like? I can't reproduce the error with incorrect `flow.json`. Also, are you using the latest version of the CLI?
