### ISSUE TITLE
Code inside destroy() block does nothing

### ISSUE THREAD

**Issue by wow64bb** [onflow/flow-cli#398]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Basically, anything that's inside `destroy()` would not work. A simple log or even removing the thing (aka just leave destroy() with empty function) still works.

The below still works.
```
destroy()  {
}
```

### Steps to Reproduce

- Simply try putting some logging stuffs inside destroy() or remove everything from destroy(), function still works as expected but code inside would not get executed

**Comment by sideninja** [comment]
Are you describing Cadence code? are you running emulator in verbose mode with `-v` flag?

**Comment by wow64bb** [comment]
Can I see your source code? @bluesign
