### ISSUE TITLE
Contract init method arguments examples

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#399]
### Issue To Be Solved

There are no code examples for how to pass arguments to the `init` function of a contract, from the `flow.json` file.

### (Optional): Context

Many contracts require initialization arguments of various types, and there is no clear description of how to specify this in `flow.json` or how to pass these arguments using the flow cli. Examples should be comprehensive, and both `flow.json` and cli examples should be co-located for easy review.

**Comment by sideninja** [comment]
This was solved as seen here https://github.com/onflow/flow-cli/blob/master/docs/deploy-project-contracts.md#initialization-arguments
