### ISSUE TITLE
script execution does not resolve contract address from config source

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-cli#405]
### Problem

Executing simple script like this:

import FungibleToken from "cadence/contracts/FungibleToken.cdc"
import FlowToken from "cadence/contracts/FlowToken.cdc"

pub fun main(address: Address): UFix64 {
	let acct = getAccount(address)
	let vaultRef = acct.getCapability(/public/flowTokenBalance)!.borrow<&FlowToken.Vault{FungibleToken.Balance}>()
		?? panic("Could not borrow Balance reference to the Vault")
	return vaultRef.balance
}

fails with a following error when the command is not run from the same directory where the script is located:
% flow scripts execute -n localnet ./code/simple_script.cdc 0xe9dd1081676bbc90
❌ Command Error: import cadence/contracts/FungibleToken.cdc could not be resolved from the configuration

When I execute the same script from the directory wher eit is located it succeeds:
% flow scripts execute -n localnet ./simple_script.cdc 0xe9dd1081676bbc90 
Result: 9999.90100000

### Context

Cli version: Version: v0.28.3
The command was run agains a localnet

**Comment by bluesign** [comment]
This is related to: https://github.com/onflow/cadence/issues/1132

**Comment by sukantoraymond** [comment]
@bluesign Hi! is the local file resolution from https://github.com/onflow/cadence/issues/1132 ever implemented in cadence? Or is a specific fix needed in the cli? Thanks!

**Comment by bluesign** [comment]
@sukantoraymond I totally forgot that, but I think it can be in CLI ( LS should have the code , so basically just using that also can be ok )

**Comment by sideninja** [comment]
This should be fixed.
