### ISSUE TITLE
Invalid defaults for `flow events get <event-type>` command

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-cli#407]
### Problem

I tried using `flow events get` command to fetch a certain type of event in some block range for my local emulator network. I executed bellow comamnd, which returned the corresponding output:
```shell
$ flow events get A.0ae53cb6e3f42a79.FlowToken.TokensWithdrawn          
❌ Command Error: cannot have end height (1) of block range less that start height (18446744073709551607)
```

The default value for `--start` flags is invalid. It should probably be equal to `0`, if using local emulator network.

This issue also occured when I tried using the `--last` flag:

```shell
$ flow events get A.0ae53cb6e3f42a79.FlowToken.TokensWithdrawn --last 20        
❌ Command Error: cannot have end height (1) of block range less that start height (18446744073709551597)
```

Further on, this command also has unexpected behaviour when values are explicitly provided via flags. For example I provided both `start` and `end` flag, but command still complained:
```shell
$ flow events get A.0ae53cb6e3f42a79.FlowToken.TokensWithdrawn --start 0 --end 1
❌ Command Error: please provide either both start and end for range or only last flag
```

### Steps to Reproduce

1. Run flow emulator
2. Create some transactions that contain at least a single event (test data)
3. Execute `flow events get <event-type>` command (see examples)

### Context

I wanted to retrieve event information, that would help me with debugging this issue: https://github.com/onflowser/flowser/issues/62.

**Comment by sideninja** [comment]
This has been fixed but awaits a release, one will come this week. https://github.com/onflow/flow-cli/commit/3065b5ec5a3faca222672795d0cc64d16e8211b7
