### ISSUE TITLE
Document includes flag in ´flow transactions get´

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#424]
### Problem
```flow transactions get```has an --include option but it is not doucmented in the cli help what values can be specified. 

### Steps to Reproduce

```flow transactions get -h```does not show include values

### Acceptance Criteria

The include values are documented with examples. Both in cli output and on web.

**Comment by bjartek** [comment]
It also appears that it is only in the text output that fields are hidden by default. In json output everything is present

**Comment by sideninja** [comment]
Added in doc PR #445
