### ISSUE TITLE
why use cmd `flow init` created the same account's address?

### ISSUE THREAD

**Issue by laizhenxing** [onflow/flow-cli#434]
I use the command `flow init` to create flow.json. But everytime the account's address is 'f8d6e0586b0a20c7'. What's the reason? Can I create different account's address? How to do this?

**Comment by sideninja** [comment]
Account creation on Flow is a bit different to other blockchains, you can read more about it here: https://docs.onflow.org/concepts/accounts-and-keys/ 
So to quickly answer your question you can't create a different first account address as they are defined by the network. 
For future I encourage you to ask this kind of questions in our discord https://discord.com/channels/613813861610684416/613813861610684421 as this is not an issue.
