### ISSUE TITLE
Total Tokens Staked is no longer reported

### ISSUE THREAD

**Issue by Kay-Zee** [onflow/flow-cli#435]
### Problem

`Total Tokens Staked` field in `flow accounts staking-info` returns nil ever since the contract upgrade of the staking contract during Mainnet 9.

### Steps to Reproduce

`flow --host=access.mainnet.nodes.onflow.org:9000 accounts staking-info 8a3adc67b40156bf`

### Acceptance Criteria

We need to either provide an additional function to get this info, or fix the retrieval of this data

### Context

Some partners want to know total tokens staked for a node (including delegators). This is no longer reported using `flow accounts staking-info`

<img width="545" alt="Screen Shot 2022-01-03 at 2 42 35 PM" src="https://user-images.githubusercontent.com/2775157/147988344-8138278d-0308-42cb-b005-92118e9ccb40.png">

**Comment by janezpodhostnik** [comment]
I can take this since I was doing something similar today.
