### ISSUE TITLE
Add more examples of sending a transaction via Flow CLI 

### ISSUE THREAD

**Issue by muttoni** [onflow/flow-cli#441]
### Issue To Be Solved

There was a back and forth on a Discord (Emerald DAO), mentioning that the [Flow CLI transaction docs](https://github.com/onflow/flow-cli/blob/master/docs/send-transactions.md) are not clear/comprehensive when it comes to flags/options and usage (e.g. multiple arguments, different argument types, different flag combinations).

Given that we also get frequent questions about how to pass in arguments in Flow CLI transactions on our own Discord channels as well, I am creating this issue so we remember to make that page more comprehensive in terms of usage examples and explanations. 

Page in question: https://github.com/onflow/flow-cli/blob/master/docs/send-transactions.md

**Comment by Bamthelearner** [comment]
Would be good if there are demonstrations on how to make cadence code with 
```import FungibleToken from "../contracts/FungibleToken.cdc"``` runnable on Flow CLI.

**Comment by mrpowergage** [comment]
Example to delete a contract from testnet:

`flow transactions send [file path] —network=testnet —signer=testnet-account`

```
// [file path]
transaction {
  prepare(acct: AuthAccount) {
    acct.contracts.remove(name: "[Contract Name");
  }
}
```

**Comment by mrpowergage** [comment]
Instructions as to how to check it's been deleted also useful. By which I mean using

https://flow-view-source.com/testnet/account

I know it's not strictly part of this issue. But as a newbie it's exactly the sort of place I've fallen down, not knowing how to query the account.

**Comment by sideninja** [comment]
@mrpowergage for removing contracts you should use the `flow accounts remove-contract` command https://docs.onflow.org/flow-cli/account-remove-contract/

@muttoni I will try add more examples, are there specific examples that can be added (beside some combinations with flags) 

@Bamthelearner not sure what you mean? Doesn't that import work if you are using the CLI? Assuming of course you have that in flow.json as described https://docs.onflow.org/flow-cli/project-contracts/

**Comment by Screendead** [comment]
@sideninja `flow accounts remove-contract` is only available for an emulator environment - we were trying to remove a contract on testnet.

**Comment by Screendead** [comment]
I think it would be really useful for the flow project deploy command to spit out either 1) or 2) when it fails due to a contract being too different from its deployed version:
1) To remove the existing contract run flow project remove <contract name>
or 2) To force deploy (removes existing contracts if they conflict with updates) run flow project deploy --force

**Comment by mrpowergage** [comment]
Reflecting, I think my main bit of feedback on the documentation is that missed that there was one simple command that executes all the phases of the transaction, rather the documentation led us to think that we needed to build the transaction first, then send, then sign, which took us a chunk of time working out. IT would be good if those pages could highlight that there is a combined command.

**Comment by sideninja** [comment]
> @sideninja `flow accounts remove-contract` is only available for an emulator environment - we were trying to remove a contract on testnet.

Wow, that's a good flag about removing contracts, not sure why there is this inconsistency but this is a major UX issue in my opinion, I will take a look at that and get back to you.

@mrpowergage I'm starting to feel like we should have a general transaction page explaining how to handle different transactions etc. Will flag that and hopefully soon can fix it.

**Comment by sideninja** [comment]
@muttoni @mrpowergage it turns out I've already written a more extensive doc on transaction examples a while ago but for some reason wasn't published on doc page. I will make sure it gets published now.
https://github.com/onflow/flow-cli/blob/master/docs/complex-transactions.md

**Comment by sideninja** [comment]
@Screendead as it turns out you can already remove contracts on testnet using that command, not sure why docs says you can't I will make sure to fix that.

You can try that by using:
```flow accounts remove-contract Kibble --signer alice --network testnet```
*just make sure alice is defined in your flow.json*

**Comment by sideninja** [comment]
@muttoni I think I've addressed all the issues. The PR with all that is here: https://github.com/onflow/flow-cli/pull/445

**Comment by sideninja** [comment]
> I think it would be really useful for the flow project deploy command to spit out either 1) or 2) when it fails due to a contract being too different from its deployed version:
> 
> 1. To remove the existing contract run flow project remove 
>    or 2) To force deploy (removes existing contracts if they conflict with updates) run flow project deploy --force

Funny enough I had a todo https://github.com/onflow/flow-cli/blob/master/pkg/flowkit/services/project.go#L194
Can you make that as a separate issue? so we can keep track of this improvement.

**Comment by muttoni** [comment]
Thanks @sideninja <3
