### ISSUE TITLE
"Force-deploy" feature request

### ISSUE THREAD

**Issue by Screendead** [onflow/flow-cli#452]
### Issue To Be Solved

I think it would be really useful for the `flow project deploy` command to spit out something like the following when it fails due to a contract being too different from its deployed version:

"To force deploy (removes existing contracts if they conflict with updates) run `flow project deploy --force`"

This command would ideally delete existing contracts whose code conflicts with the incoming changes (such as different numbers of variables on the contract), and replace them entirely with the new code.

### (Optional): Context

Suggestion resulted from discussion on issue #441 --> https://github.com/onflow/flow-cli/issues/441#issuecomment-1019492159

Thanks for your work guys, appreciate you.

**Comment by sideninja** [comment]
Great feedback. This should be released in the next major version.

**Comment by bluesign** [comment]
Does this work on testnet? I mean remove and deploy incompatible contract part.

Afaik, you cannot remove and deploy incompatible one.

**Comment by sideninja** [comment]
@bluesign it works on the emulator so it could be a nice addition, I anyhow feel the testnet shouldn't be used for that kind of operations. Testnet shouldn't be used for such drastic updates. But tbh not sure, I would have to check for testnet once this gets scheduled but in any case it might be wise to disable on testnet.

**Comment by Screendead** [comment]
Awesome work, thanks @sideninja!
