### ISSUE TITLE
Add the link to the testnet faucet when generating keys via the CLI.

### ISSUE THREAD

**Issue by srinjoyc** [onflow/flow-cli#455]
## Instructions

When calling `flow keys generate`, the intention for the user is often to create a testnet account. We should add a link to the testnet faucet to the output of the command above. Ideally, we can pass the public key as a URL parameter so the user can get a testnet account in two clicks from the CLI.

**Comment by sideninja** [comment]
What is the faucet URL? https://flow-faucet.vercel.app/?
