### ISSUE TITLE
flow.json contract deploy import substitution

### ISSUE THREAD

**Issue by adhurjaty** [onflow/flow-cli#483]
### Problem

I'm unable to do the import substitution in a contract when trying to deploy to the emulator

here's my flow.config
```
{
    "emulators": {
        "default": {
            "port": 3569,
            "serviceAccount": "delphai"
        }
    },
    "contracts": {
        "DelphaiUsers": {
            "source": "./cadence/contracts/DelphaiUsers.cdc",
            "aliases": {
                "emulator": "f8d6e0586b0a20c7"
            }
        },
        "FungibleToken": {
            "aliases": {
                "emulator": "ee82856bf20e2aa6"
            }
        },
        "FlowToken": {
            "aliases": {
                "emulator": "0ae53cb6e3f42a79"
            }
        }
    },
    "networks": {
        "emulator": "127.0.0.1:3569",
        "mainnet": "access.mainnet.nodes.onflow.org:9000",
        "testnet": "access.devnet.nodes.onflow.org:9000"
    },
    "accounts": {
        "delphai": {
            "address": "f8d6e0586b0a20c7",
            "key": "06272ec1c8367f040e3cfa7d9b11cb81bc6c0e77cf774777e5573dc4b8566aaa"
        }
    },
    "deployments": {
        "emulator": {
            "delphai": [
                "DelphaiUsers"
            ]
        }
    }
}
```

I'm trying to import the FungibleToken this way
```
import FungibleToken from 0xFungibleToken
```

I'm running the emulator: `flow emulator --contracts`
and attempting to deploy with flow deploy emulator
The error I'm getting is
```
error: unexpected token: identifier
 --> :1:29
  |
1 | import FungibleToken from 0xFungibleToken
  |                              ^
```
I'm expecting the flow CLI to know to replace `FungibleToken` with the address `ee82856bf20e2aa6`. I get no error if I do the replacement in code directly
I'm using flow-cli v0.31.1 and on Ubuntu 20.04.

**Comment by sideninja** [comment]
Thank you for this feedback, but unfortunately, currently, the only way this would work is for you to reference the import contract in the source code by its file location (example: `import FungibleToken from ./FungibleToken.cdc`) which means you have to have that contract saved locally. This is the problem we are aware of and trying to provide a better import support as [defined here in the FLIP](https://github.com/onflow/flow/blob/906067ffcaf107a0b66b726c6f23d98b0e72dd89/flips/2022-03-23-contract-imports-syntax.md)

**Comment by adhurjaty** [comment]
Thanks @sideninja. If I do that, then I encounter a problem with the `FlowToken` contract. It requires a parameter in the constructor. How do I use `flow.json` to pass the `AuthAccount` parameter?

**Comment by sideninja** [comment]
You can use init arguments as seen here https://docs.onflow.org/flow-cli/deploy-project-contracts/#initialization-arguments but you only can pass these values https://docs.onflow.org/cadence/json-cadence-spec/ 
Can you share the contract you want to deploy so I can take a look at it?
