### ISSUE TITLE
Flow CLI does not takes in the intended account on projects deploy

### ISSUE THREAD

**Issue by Bamthelearner** [onflow/flow-cli#487]
### Problem

When using Flow CLI command for project deployment. The account is not taken as intended, Instead it takes the first account with the same address for deployment for signing the transaction.

### Steps to Reproduce
Here is my flow.init set up:
```
	"accounts": {
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "ae1b44c0f5e8f6992ef2348898a35e50a8b0b9684000da8b1dade1b3bcd6ebee"
		},
		"emulator-account-2": {
			"address": "4ada5fbd7073699b",
			"key": "Not shown as it is not important"
		},
		"testnet-account" : {
			"address": "4ada5fbd7073699b",
			"key": {
				"type" : "hex",
				"index" : 0,
				"signatureAlgorithm" : "ECDSA_secp256k1",
				"hashAlgorithm" : "SHA3_256",
				"privateKey" : "Not shown as it is not important",
				"publicKey" : "Not shown as it is not important"
			}
		},
```

And here are the contracts that I want to deploy : 
```
	"deployments": {
		"testnet" : {
			"testnet-account" : [
				"Voter", "ArleeScene", "Arlequin"
			]		
		}
	}
```

As you can see, I have the same account address for "emulator-account-2" and "testnet-account" 
So when I run flow project deploy -n=testnet

Errors returned : 
```
 Error deploying Voter: ([Error Code: 1006] invalid proposal key: public key 0 on account 4ada5fbd7073699b does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account 4ada5fbd7073699b does not have a valid signature: signature is not valid)
 ```
 
 It might be the issue that, flow CLI is checking for the first address that come into sight which has the same address as the deploying contracts target address. Therefore the account info in "emulator-account-2" is taken instead of "testnet-account".
 
 After deletion of the "emulator-account-2" object, the transaction can then run and successfully deploy the contracts.
 
 Flow CLI should be programmed so that even I have a few accounts with the same address, it still uses the correct target account that I intended while running flow project deploy.

**Comment by Bamthelearner** [comment]
Thank you @bjartek very much for spending the time with me.
He discovered this!
I am pinging you to see if you have any comment on this

**Comment by sideninja** [comment]
Thank you for great report. Looking at the code now it seems you are right, this line https://github.com/onflow/flow-cli/blob/master/pkg/flowkit/services/project.go#L163 just fetches the account by address, not name - due to the contract not even including names of the account. Will make this a high priority for the next release.
