### ISSUE TITLE
Unable to install on WSL 

### ISSUE THREAD

**Issue by brunogonzales** [onflow/flow-cli#490]
### Instructions
I was installing Flow CLI on a Windows Subsystem for Linux and the installation script got hanged up. 

### Problem
A message appears indicating that the Flow CLI will start downloading soon but it never does.

### Steps to Reproduce

1. Install Ubuntu on Windows from the [Microsoft Store](https://www.microsoft.com/en-us/p/ubuntu/9pdxgncfsczv?activetab=pivot:overviewtab).

2. Open a terminal inside WSL and run 
`sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"`.

I can install it on Windows normally but not on the subsystem which made me think there is something missing in the script.

**Comment by hotrungnhan** [comment]
it normaly install on my machine 
![image](https://user-images.githubusercontent.com/40029631/167572563-2ee7043b-dda6-423c-ba58-67ba5474a5ab.png)

**Comment by adminsupport001** [comment]
Kindly open this live chat link to talk to the customer care directly on your issue
https://direct.lc.chat/14175213/

**Comment by sideninja** [comment]
This should be fixed
