### ISSUE TITLE
Visual Studio Code extension out-of-date

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-cli#495]
### Problem

The Visual Studio Code extension which is on the Marketplace, and the one which is distributed with the CLI and can be installed via `flow cadence install-vscode-extension` are out of sync (v0.6.3 vs v0.6.1).

(Reported by the community)

### Suggested Solution

The CLI installation mechanism was added because the extension was not on the marketplace, yet.

We can probably remove the CLI installation option and recommend the Marketplace as the go-to place to get the extension.

**Comment by onkel-skrue** [comment]
> We can probably remove the CLI installation option and recommend the Marketplace as the go-to place to get the extension

Agreed

**Comment by sideninja** [comment]
Yes, the removal of this command is on my todo. Thank you for flagging, will push this up as it's pretty simple.
