### ISSUE TITLE
make `flow project deploy` smarter

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#498]
## Instructions

Right now flow project deploy either allow you to deploy all contracts or update all contracts. If you have an account with several contracts and change just one having to wait until everything deploys takes time. 

I propose to make the command smarter in that it will look at chain to see what is there and do the right thing. We can even add a --diff flag to allow it to show diffs that will be deployed incase of update. 

I have some code in overflow for doing this, granted this is used for mainnet deploy but the pattern is the same. 
https://github.com/findonflow/find/blob/main/tasks/deploy/main.go

### Issue To Be Solved

Make it faster and funnier to deploy contracts onflow!

**Comment by sukantoraymond** [comment]
Just wondering if we need to implement --force, because with --update we only update if there is diff with existing contract in account. If there is no diff, then there's no point to update the contract with --force? 

My point is that we can just update the current implementation of --update, such that it updates ONLY if there is diff.

**Comment by sukantoraymond** [comment]
Unless we want to make it such that --update has to first show the diff for each contract and we give option of (y/n) for the user to choose. If user chooses y, then we do the update. With --force, we won't show this preview and just update all the contract that has diff

**Comment by bjartek** [comment]
> Unless we want to make it such that --update has to first show the diff for each contract and we give option of (y/n) for the user to choose. If user chooses y, then we do the update. With --force, we won't show this preview and just update all the contract that has diff

This was what I had in mind, that you do not show prompts and just update with --force flag
