### ISSUE TITLE
Integrate community built tools

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#501]
After the initial discovery, the best way to proceed with the integration of dev-tools into CLI is to set up an environment for the dev tool as part of the install process, imagine having a command like `flow flowser` which would then check if required environments (node) are installed at that point it would fetch the remote build and run it locally. 

This would also require good documentation of the process so others could follow the steps and get included in the CLI. This way the CLI would allow plug and play functionality. The CLI commands would also be restructured for better readability, an example is:

There could be a new section of development tools in the CLI to which community-built tools would be added as well.
```
Development Tools:
emulator     Starts the Flow emulator server
wallet       Starts the development wallet service
```

**Comment by bjartek** [comment]
I plan to add support to bootstrap an overflow project and having that as a subcommand in flow would be amazing.

**Comment by sideninja** [comment]
Yep. Let's discuss it. We plan to add new tools to the CLI soon. Can you explain what would the bootstrap involve?

**Comment by bjartek** [comment]
https://github.com/onflow/developer-grants/issues/87
