### ISSUE TITLE
Got error after upgrade Flow-cli 0.35.0 on MacOs 10.15.2 (Intel chips)

### ISSUE THREAD

**Issue by caosbad** [onflow/flow-cli#514]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Got some error after upgrade Flow-cli 0.35.0 on MacOs 10.15.2 (Intel chips)

### Steps to Reproduce

run 
`sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v0.35.0`

### Context
After install the 0.35.0 version flow-cli
![](https://cdn.discordapp.com/attachments/982573969150451762/982574250240147456/unknown.png)
Got error

Then I downgrade to v0.33.1-sc-m5 it works

**Comment by sideninja** [comment]
Can you try removing the binary at that location and re-run install, you should have it at `/usr/local/bin/flow`.

**Comment by caosbad** [comment]
Yeah I‘ve try re install the Flow-cli same error
And using brew install flow-cli got old version 0.29 , any other idea?

**Comment by sideninja** [comment]
@caosbad if you using the brew you should get the latest version, so that's really weird. Could you try running `brew upgrade flow-cli` I have a feeling you might have something broken with your local flow CLI binary.

**Comment by caosbad** [comment]
Thx, Im trying upgrade now 
and the result of `which flow` is  /usr/local/bin/flow

**Comment by caosbad** [comment]
![image](https://user-images.githubusercontent.com/10805199/172523450-39fd173b-880d-4f33-abe5-4d003a6a7d30.png)
Still the old version after brew upgrade flow-cli

**Comment by caosbad** [comment]
After brew I got the 0.35.0 version, thx
