### ISSUE TITLE
Multisign support

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-cli#524]
Currently multisign support in flow-cli is lacking and I think this is causing dangerous ( maybe also embarrassing ) workflows.  ( example: https://github.com/onflow/service-account/tree/main/transactions )

I think we need to add some secure multisign support.

**Comment by sideninja** [comment]
You can use sign and send-signed commands no?

**Comment by bluesign** [comment]
Problem is I think it is prone to error/abuse. In the example flow I showed, people signing sequentially. So if I am the first signer and replace the payload, probably it would go unnoticed. 

Better flow would be everyone signing independently, and sender takes multiple signed payloads and sign as payer I guess.

**Comment by sideninja** [comment]
When you do the send-signed and sign command it shows the payload of the transaction for you to confirm. 

On the other point of independently signing, I need to take a look into it and I will let you know.

**Comment by bluesign** [comment]
Thank you very much, it is currently pretty good actually (for current design goal, which I totally missed ), my proposal is a bit improvement ( especially for contract update cases for example ) 

PS: Actually I saw this when I am designing a flow for multisign orchestration on chain. ( So totally different design goals )

**Comment by sideninja** [comment]
Can you elaborate a bit more on that use case?

**Comment by bluesign** [comment]
Something like: you have something to multisign (lets say you need 5/20 signatures), you publish it as a proposal, signatures coming in, when threshold reached you send to network.

**Comment by sideninja** [comment]
I see, that makes sense yeah!

**Comment by bluesign** [comment]
I am closing this issue, as most of the multisign solutions are single account with multiple keys ( different weights ), as they are all signing the envelope, order doesn't matter much.
