### ISSUE TITLE
Add support for init() arguments in `flow accounts add-contract` command

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-cli#529]
### Issue To Be Solved

Currently if you use `flow accounts add-contract` command, you have no way to provide initialization arguments to `init(...args)` function.

For example, I've defined a deployment config with the required arguments in projects `flow.json`:
```json
"deployments": {
    "emulator": {
      "emulator-account": [
        {
          "name": "FlowTea",
          "args": [
            { "type": "Address", "value": "0xf8d6e0586b0a20c7" },
            { "type": "UFix64", "value": "0.05" }
          ]
        }]
    }
  }
```

But this configuration is not used in `add-contract` command:
```
flow accounts add-contract FlowTea ./cadence/contracts/FlowTea.cdc
Transaction ID: 3a2a2a89a9d3e0e10843ae1511eecd32b440bccdbc5e9f7b760e23146dd263d5
❌ Failed to deploy contract
❌ Command Error: execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:
error: invalid argument count, too few arguments: expected 2, got 0, next missing argument: `Address`
 --> 3a2a2a89a9d3e0e10843ae1511eecd32b440bccdbc5e9f7b760e23146dd263d5:4:3
  |
4 | 			signer.contracts.add(name: name, code: code.decodeHex() )
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Suggest A Solution

This command should probably read the configuration provided via `flow.json` file, similar to `flow deploy` command.

**Comment by bluesign** [comment]
I think we can also add support to adding/updating contract without contract name with this issue, args can be parsed from command line. ( We can detect if first parameter is filename I guess.  ) 

I think both should be valid for backwards compatibility for some time. 

`flow accounts add-contract ./cadence/contracts/FlowTea.cdc meow woof`
`flow accounts add-contract FlowTea ./cadence/contracts/FlowTea.cdc meow woof`

**Comment by sideninja** [comment]
Yes. I opened an issue for that sometime ago https://github.com/onflow/flow-cli/issues/231
