### ISSUE TITLE
Get Transactions not possible anymore after Mainnet update

### ISSUE THREAD

**Issue by fyrz** [onflow/flow-cli#530]
### Problem

It is not possible to retrieve transactions anymore via flow-cli. 

### Steps to Reproduce

flow transactions get 89c1bc3b9e38d17341a681b813239daa2d0a577c0544c2015b701f9070a0f4bb -n mainnet -o json

### Acceptance Criteria

Retrieve like before Json output from requested command.

### Context

Blocks our airdrops.

**Comment by sideninja** [comment]
It's possible to retrieve the transactions with the CLI, but the problem you are experiencing is related to spork, unfortunately if you use the default mainnet AN you can only retrieve data in the current spork, you can't travel between sporks (spork is a network upgrade). In order to achieve that you need to reference a previous spork AN. cc @vishalchangrani can you help here? what is the previous AN address?

**Comment by bluesign** [comment]
@sideninja to my surprise, protocol state is moving across sporks. ( I learned this just 2-3 days ago ) 

I think this is known bug on cadence side. Related to Type encoding changes. I think this PR will fix: https://github.com/onflow/cadence/pull/1734#event-6831177319

**Comment by fyrz** [comment]
@bluesign @sideninja the issue is still there.

**Comment by sideninja** [comment]
We've added the ability to decode the previous format in the Go SDK, need to update the CLI to resolve this problem I believe.

**Comment by fyrz** [comment]
@sideninja works not really. Still many transactions failing. Do you need testdata ?

**Comment by sideninja** [comment]
I meant that it still needs to be updated in the CLI. I will take a look at this today once I find the time. Sorry for the delay. You can send me a transaction ID so I can test yeah.

**Comment by sideninja** [comment]
Also can you confirm which flow CLI version you have and that it's updated to latest `Version: v0.37.4`

**Comment by bluesign** [comment]
This is not possible to fix on flow-cli side without some ugly hacks. I think cadence should support encoding to old format.
