### ISSUE TITLE
Windows CLI does not accept array of strings as a parameter

### ISSUE THREAD

**Issue by zaneousryan** [onflow/flow-cli#534]
I am hitting what feels like a bug in the CLI on windows but I am sure I am just messing something up. 
I am trying to send a transaction but I am getting an error based on my paramaters. I am not sure but I believe this is how a [String] should be passed in 
flow -n testnet transactions send C:\Development\ContractsOnFlow\transactions\mint_nft.cdc "0xcxxe5a9b72b5ad08" "Test" "description here" "creatorId" "creatorname" "createdDateTime" "location" "https://en.wikipedia.org/wiki/File:Golde33443.jpg" '[0.1]' '["SILL Fee"]' '[0xcxxe5a9b72b5ad08]' --signer testnet-account
I get error " Command Error: error parsing transaction arguments: argument royaltyDescriptions is not expected type [String]"
'["SILL Fee"]' is what I am passing in for this argument. Do I have this formatted in correctly? Here is the transaction argument code
transaction(
    recipient: Address,
    name: String,
    description: String,
    creatorId: String,
    creatorName: String,
    createdDateTime: String,
    location: String,
    thumbnail: String,
    cuts: [UFix64],
    royaltyDescriptions: [String],
    royaltyBeneficiaries: [Address] 
) {

Seems passing any array of strings in the CLI causes the CLI to reject the parameter as not an array of strings. I found this by passing in the above command. 
I need it to accept string arrays properly, or to understand the proper format so I can test using CLI

**Comment by bluesign** [comment]
Did you try escaping ? 

something like : 

```
flow -n testnet transactions send x.cdc "0xc12e5a9b72b5ad08" "Test" "description here" "creatorId" "creatorname" "createdDateTime" "location" "https://en.wikipedia.org/wiki/File:Golde33443.jpg" "[0.1]" "[\"SILL Fee\"]" "[0xc12e5a9b72b5ad08]"
```

**Comment by zaneousryan** [comment]
This works flow -n testnet transactions send x.cdc "0xc12e5a9b72b5ad08" "Test" "description here" "creatorId" "creatorname" "createdDateTime" "location" "https://en.wikipedia.org/wiki/File:Golde33443.jpg" "[0.1]" "[\"SILLFee\"]" "[0xc12e5a9b72b5ad08]"

but this is seeing 12 parameters instead of 11
flow -n testnet transactions send x.cdc "0xc12e5a9b72b5ad08" "Test" "description here" "creatorId" "creatorname" "createdDateTime" "location" "https://en.wikipedia.org/wiki/File:Golde33443.jpg" "[0.1]" "[\"SILL Fee\"]" "[0xc12e5a9b72b5ad08]"
Do I need to escape the space in the string some how as well ([\"SILLFee\"] vs "[\"SILL Fee\"])

**Comment by bluesign** [comment]
yeah should be like this: `"[\"SILL Fee\"]"`, space shouldn't be problem actually. 

Btw if you write your message between \` GitHub shows the raw version

**Comment by ObjectPlayer** [comment]
@zaneousryan Yeah I think it is cli bug, as other types of Arrays are working fine, only having issue in `[String]` but to solve this issue you can try, `args-json`  flag to pass your `[String]` argument. Hope it will work:

e.g:

`flow -n testnet transactions send C:\Development\ContractsOnFlow\transactions\mint_nft.cdc --args-json '[ {"type":"Address", "value":"0x5b2b52bfa03fafac"}, {"type":"String", "value":"Test"}, {"type":"String", "value":"description here"}, {"type":"String", "value":"creatorId"}, {"type":"String", "value":"creatorname"}, {"type":"String", "value":"createdDateTime"}, {"type":"String", "value":"location"}, {"type":"String", "value":"https://en.wikipedia.org/wiki/File:Golde33443.jpg"}, {"type":"Array", "value":[{"type":"UFix64", "value":"0.1"}]}, {"type":"Array", "value":[{"type":"String", "value":"SILL Fee"}]}, {"type":"Array", "value":[{"type":"Address", "value":"0x5b2b52bfa03fafac"}]} ]'`

**Comment by bluesign** [comment]
> yeah should be like this: `"[\"SILL Fee\"]"`, space shouldn't be problem actually.

For future readers, after reading some powershell docs seems correct escaping is: 

```
PS C:\Users\bluesign\fg> echo "[\""String with spaces\""]"
[\"String with spaces\"]
PS C:\Users\bluesign\fg> echo "[\"String with spaces\"]"
[\
String
with
spaces\]
PS C:\Users\bluesign\fg>
```
