### ISSUE TITLE
The CLI directs you to https://docs.onflow.org/flow-cli/install/ for upgrade instructions but the word "upgrade" isn't even anywhere on the page

### ISSUE THREAD

**Issue by TraeRegan** [onflow/flow-cli#536]
### Problem

The CLI directs you to https://docs.onflow.org/flow-cli/install/ for upgrade instructions but the word "upgrade" isn't even anywhere on the page

### Steps to Reproduce

Visit: https://docs.onflow.org/flow-cli/install/

### Acceptance Criteria

Upgrade instructions would actually be included on the page.

### Context

I am using `v0.36.2` and getting a warning that says:
`Version warning: a new version of Flow CLI is available (v0.37.0). Read the installation guide for upgrade instructions: https://docs.onflow.org/flow-cli/install`

But there are no upgrade instructions on the page, and when I run the following it just reinstalls `v0.36.2`:
`sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"`

**Comment by sideninja** [comment]
We should add the brew upgrade option `brew upgrade flow-cli` and for the install script if you run it should get you the latest version, however, we were late in updating what that is. I believe if you try again that should work. cc @sukantoraymond

**Comment by sideninja** [comment]
Added the docs, they should be visible after rebuild. You should also be able to update the flow-cli now with the method you mentioned, so try again. Thank you.
