### ISSUE TITLE
Flow cli does not read state of contracts correctly

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#559]
```
𝝺 flow project deploy -n testnet --update

Deploying 5 contracts for accounts: testnet-account

no diff found in Clock, skipping update
no diff found in Debug, skipping update
AeraPack -> 0x6ba02a4addfcd965 (ab2f3a84da7619a5e6ed42ab9afabd3b0a373fa95d4d557d05b944ed4ed98fb6) (update)

❌ AeraNFT error: client: rpc error: code = Internal desc = failed to find: rpc error: code = Internal desc = failed to retrieve result from execution node: 2 errors occurred:
	* rpc error: code = Canceled desc = grpc: the client connection is closing
	* rpc error: code = Canceled desc = grpc: the client connection is closing


❌ Error updating Admin: ([Error Code: 1007] invalid proposal key: public key 0 on account 6ba02a4addfcd965 has sequence number 9, but given 8)

❌ failed to deploy all contracts
❌ Command Error: failed to deploy all contracts

𝝺 flow project deploy -n testnet --update

Deploying 5 contracts for accounts: testnet-account

no diff found in Clock, skipping update
no diff found in Debug, skipping update
AeraPack -> 0x6ba02a4addfcd965 (4163289a9adba1a76f21ac6794e924029929ad61a82fc3c7a2fa7cdac3a9b658) (update)

AeraNFT -> 0x6ba02a4addfcd965 (9b053df9f4e67ddb9cec21925665c1d99dcbe9478b1ed9353d4762e64fad5040) (update)

Admin -> 0x6ba02a4addfcd965 (db4582e27d1e0e66a083a79e7d9ef9ce4784f8003a53002dc9dbf9e7dfe2b5e0) (update)

3 contracts updated successfully

✨ All contracts deployed successfully

```

As you can see in this result above i updated the AeraPack successfully but in the next line i am retrying the failed deploys and now it says that AeraPack is not the same. This has to be a bug.

**Comment by bluesign** [comment]
load balancer strikes again ( probably different AN answered get account )

**Comment by bjartek** [comment]
It happends to me when i update find v2 on testnet as well. I have _not_ updated code and it still redeploys it. I am 100% sure we have not touched the code in weeks.

**Comment by sideninja** [comment]
@sukantoraymond can you please investigate this problem.

**Comment by sukantoraymond** [comment]
In attempting to recreate this problem, I created 3 contracts, deployed all three to emulator. When I run `./flow project deploy --update`, this went ok. Then I changed the second and third contract so that there is error and when I run `./flow project deploy --update`, it  says "no diff found, skipping update" for the first one. 

This might be super edge case, maybe if @bjartek can show exact step and the contract to replicate this? Thanks!

**Comment by sideninja** [comment]
@sukantoraymond it might have to do with one of the contract updates failing.
@bjartek when updating findV2 on testnet, was there an error or it just worked but updated the contracts? can you share the address of that contract? and does that happen everytime you update that contract? @sukantoraymond maybe you can try deploying that contract yourself and seeing what is going on.

**Comment by bjartek** [comment]
https://github.com/findonflow/find fork that and change the testnet address, deploy all the code. Change something in one of the contracts like FIND and i belive it will update more of them. The v2 branch of the repo has lots more contracts.

**Comment by sideninja** [comment]
So basically if one contract has a change it's causing others to update as well. That might be a starting place @sukantoraymond 
Thanks @bjartek for reporting.

**Comment by bluesign** [comment]
I think it is related to this: https://github.com/onflow/fcl-js/issues/1320 
> During heavy network load, requests to get accounts at latest finalized block can fail. 

Need to get account at latest sealed block ( I am guessing here )
