### ISSUE TITLE
Better validation of configuration

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#60]
There should be a JSON schema validation for configuration properties. We need to validate and provide the best possible feedback to wrong values/properties to users. I think JSON schema can be a good way to achieve this, but it will be different for each format (yaml...). I believe the first step should be improving validation on the abstract configuration structures and second step could be validation of configuration files since the first step provides the feedback the value is not correct but it doesn't say where the value error is located or if the value is missing where that value should be defined.

**Comment by uhbif19** [comment]
+1 

Also, there are two formats of `flow.json` with no clear description of their differences.

**Comment by sideninja** [comment]
> +1
> 
> Also, there are two formats of `flow.json` with no clear description of their differences.

There is an old `flow.json` format that if you try using with updated CLI it shows a warning. Is that what you have in mind?

**Comment by uhbif19** [comment]
@sideninja I am not sure which one of `flow init` or `flow project init` is old one. If I recall correctly, it may sometimes require different formats for different tasks or fail without warning on using wrong format.

**Comment by sideninja** [comment]
Oh yeah the `flow project init` is getting deprecated, there is warning in the new version - I suggest you update it.
