### ISSUE TITLE
`version.txt` occasionally out of sync with latest version

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#602]
### Problem

The `version.txt` on the master branch sometimes fails to upload to the GCS bucket where pre-built binaries are published. This prevents the Linux/macOS install script from being able to install the latest version of the CLI.

Does it make any sense to just link to the `version.txt` that's on the master branch, or could that be out of sync with the binaries in GCS?

cc @sideninja @sukantoraymond

**Comment by sukantoraymond** [comment]
we can try linking the version number on pre built binaries to version.txt instead of wahts on gcs bucket

**Comment by thgaskell** [comment]
Did something change for the `v0.39.0` release? The [version text file is updated to `v0.39.0`](https://storage.googleapis.com/flow-cli/version.txt) but that binary does not appear to exist on GCS yet. The [install script](https://docs.onflow.org/flow-cli/install/#from-a-pre-built-binary) currently throws an error unless targeting an older version.

**Comment by sukantoraymond** [comment]
@thgaskell Thanks for flagging this. We have edited the version.txt to v0.38.1
