### ISSUE TITLE
Error deploying a project to testnet: invalid signature

### ISSUE THREAD

**Issue by BlockchainFreak** [onflow/flow-cli#610]
### public key on the account does not have a valid signature

I am trying to deploy a project on testnet
`flow project deploy --network=testnet`

It shows the given error
`Error deploying Domains: ([Error Code: 1006] invalid proposal key: public key 0 on account 3e3c2b33d3c8cd61 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account 3e3c2b33d3c8cd61 does not have a valid signature: signature is not valid)`

I tried updating the flow-cli to 0.38.0 but it is not helping.
The account I used is a testnet account and I am sure that it has correct address and private key in flow.json

**Comment by sukantoraymond** [comment]
Will look into this thanks @BlockchainFreak

**Comment by sukantoraymond** [comment]
Hey @BlockchainFreak I just tried project deploy command on testnet on my end and it works fine. Can you try again with newest flow cli version?

**Comment by BlockchainFreak** [comment]
Upgrading the Flow CLI to v0.39.1, and initializing a new project helped. Finally, I was able to deploy the project on testnet.
