### ISSUE TITLE
Notify when new version is available for download.

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#65]
### Issue To Be Solved

It's not always easy to know when an upgrade has been released for the CLI. There are a lot of new features planned and it would be great if CLI users were informed about available upgrades as soon as they are available.

### (Optional): Suggest A Solution

- CLI can notify users by printing a message in the terminal.
- Message could include platform-specific upgrade instructions 

### (Optional): Context

We may want to leave the actual upgrade process up to users and specific package managers, instead of having code in the CLI to perform the upgrade.

**Comment by sideninja** [comment]
This is an important issue based on feedback from the developers. Often developers complain not having some commands available or are confused about the version/update process. I believe this issue should also include:
- warning there is a new version available
- beta versions possible to install (early use of commands etc)
- option to update within CLI
- show what is new in the new version (include release notes)
