### ISSUE TITLE
Can't generate keys with specific hash algorithm

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-cli#657]
### Instructions

Previously we could generate keys with a specific hash algorithm.
It appears that `SHA3_256` is the default hash algorithm.

### Problem

The cli should take a `--hash-algo` argument to be able to specify the hash algorithm.

### Steps to Reproduce

flow keys generate --sig-algo="ECDSA_P256" --hash-algo="SHA2_256"

### Acceptance Criteria

`flow keys generate --sig-algo="ECDSA_P256" --hash-algo="SHA3_256"`

show work

### Context

<what are you currently working on that this is blocking?>

**Comment by sideninja** [comment]
Hash algorithm is not settable during key generation but predefined for Flow keys

**Comment by cybercent** [comment]
Hi @sideninja 

I see it's defined here:
https://github.com/onflow/flow-cli/blob/6c240a76ec2bb5d5685afeb0898eed0ea1bd0059/internal/config/init.go#L38

Any reason not to allow people to use `SHA2` when generating keys?

**Comment by bluesign** [comment]
@cybercent hash algo is not part of the key, there is no difference between SHA2 or SHA3 there, keys are only used for signing. 

`SIGN(HASH(data), private_key)`

**Comment by cybercent** [comment]
@bluesign thanks, makes sense.
