### ISSUE TITLE
Release latest flow-emulator version in flow-cli

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-cli#658]
### Issue To Be Solved

There was a pretty critical (depending on the usage) bug in flow-emulator, described here: https://github.com/onflow/flow-emulator/issues/188.

This bug was already fixed (see https://github.com/onflow/flow-emulator/pull/199) and released in the latest flow-emulator version: https://github.com/onflow/flow-emulator/releases/tag/v0.36.0.

But that flow-emulator release wasn't included in any flow-cli release yet. Read the context below, to learn why this is important.

### Context

While this issue may not be affecting a lot of regular flow-cli users, but it is however blocking the release of Flowser desktop app (developed in the scope of https://github.com/onflow/developer-grants/issues/27).

Our tool (Flowser) uses the flow-cli version that's installed on the user's local machine. But all latest versions of flow-cli are affected by the issue described above, which breaks most of the Flowser functionalities (makes them unusable).

**Comment by sideninja** [comment]
Released
