### ISSUE TITLE
Flag to specify location of flow.json

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#67]
Currently you have to run commands from the directory where the flow.json file is located. 
It would be great if users could point to the location using a flag, in situations where it's not ideal to run the command from the same directory as the file.

eg:
```
flow deploy --config ../../flow.json
```

**Comment by sideninja** [comment]
Do you mean for `project deploy`? This will be solved with the current migration of the configuration we are working on. For other commands (beside project) you have a flag `--config-path`.

**Comment by 10thfloor** [comment]
> Do you mean for `project deploy`? This will be solved with the current migration of the configuration we are working on. For other commands (beside project) you have a flag `--config-path`.

Great sounds like we can close this when those changes are merged.

**Comment by sideninja** [comment]
Implemented in #101
