### ISSUE TITLE
FLOW CLI is incredibly vague on which contracts failed to deploy

### ISSUE THREAD

**Issue by harshnambiar** [onflow/flow-cli#675]
Problem: 
The FLOW CLI just outputs "Command Error: failed to deploy all contracts". It would be nicer if it summarized at the end which ones failed to deploy for what reason. A little bit of data clustering would make the error message more meaningful and less useless.

Steps to Reproduce:
Just do "flow project deploy --network testnet" in the root folder of any flow project.

Recommended Output:
"Command Error: Some contracts failed to deploy. 3 Passed and 2 Failed.
Reason for Failure: 
ContractFour: The contract is already deployed
ContractFive: Syntax Error: Missing Parenthesis"

Or something like that.

**Comment by sideninja** [comment]
@harshnambiar I think you have a very valid point and I believe the PR should fix it.
