### ISSUE TITLE
Multiple network types in Flow.json 

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/flow-cli#685]
## Overview

In FCL applications, developers can choose their desired transport to use when communicating with an Access API. The available transports in FCL are GRPC via HTTP, and REST via HTTP. 

In order for FCL applications to configure themselves resiliently using the network configuration information made available in Flow.JSON, it would need to read the specific network information for both the network it is configured with (eg: "testnet", "mainnet" etc) and also the transport that it is configured to use (eg: "grpc", "http").

## Suggestion

If we allow for multiple Access Node API URLs to be specified in Flow.json, nested by both the network and transport they represent, FCL could use this information to resiliently configure itself. 

## Example Format

```javascript
...
"networks": {
  "emulator": {
    "grpc": "127.0.0.1:3569", // <-- Used by FLOW CLI
    "grpc-http": "127.0.0.1:8080", // <-- Used by FCL (grpc transport)
    "rest-http": "127.0.0.1:8888", // <-- Used by FCL (http/rest transport)
  },
  "mainnet": {
    "grpc": "access.mainnet.nodes.onflow.org:9000",
    "grpc-http": "access-mainnet.onflow.org",
    "rest-http": "rest-mainnet.onflow.org",
  },
  "testnet": {
    "grpc": "access.mainnet.nodes.onflow.org:9000",
    "grpc-http": "access-testnet.onflow.org",
    "rest-http": "rest-testnet.onflow.org",
  }
}
...
```

**Comment by bluesign** [comment]
doesn't this conflict with https://github.com/onflow/fcl-js/issues/1479 ?

**Comment by JeffreyDoyle** [comment]
@bluesign It should work alongside the deprecation of GRPC supported outlined in https://github.com/onflow/fcl-js/issues/1479 ! - Flow.json still may want to outline grpc network addresses to be used in other tools, while FCL will still want to consume the rest/http network address

**Comment by chasefleming** [comment]
Not sure this is a big enough unlock now that REST and gRPC-Web are available using the short network domain. Going to close.
