### ISSUE TITLE
Implement CLI configuration for metrics

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-cli#686]
## Instructions
Implement persisting CLI configuration mechanism. The first thing to persist in that configuration is whether users want to disable metrics. We should create a configuration file in an established folder for configuration (based on OS) that is called something like flow-cli.config.yaml and it should store a setting for metrics being disabled. Other properties will be persisted in there in the future so make it generic preference storage not specific to metrics.

**Comment by bluesign** [comment]
https://pkg.go.dev/os#UserConfigDir
