### ISSUE TITLE
Update emulator to latest flow-go version

### ISSUE THREAD

**Issue by huyndo** [onflow/flow-cli#692]
## Instructions

Please fill out the template below to the best of your ability.

### Issue To Be Solved

Currently there's a new API on flow-go `GetNetworkParameters` from this [issue](https://github.com/onflow/flow-go/issues/2755). It is present on `testnet` and `mainnet` but not `emulator`.

### (Optional): Suggest A Solution

Update emulator to latest flow-go version

### (Optional): Context

`fcl` is exposing an interaction to grab the chain ID automatically from the access node. It's currently only working on `testnet` and `mainnet`.

**Comment by bluesign** [comment]
Yeah, we have some debt there [0] , to be honest I want to fix them too 

[0] https://github.com/onflow/flow-emulator/issues/141
