### ISSUE TITLE
Add support for Sandboxnet

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-cli#705]
## Instructions

Please fill out the template below to the best of your ability.

### Issue To Be Solved

Recently, a new test network - sandboxnet has been added. The Flow CLI needs to be updated to support this new network.

### (Optional): Suggest A Solution

(Replace this text: A concise description of your preferred solution. Things to address include:

* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

### (Optional): Context

(Replace this text:
What are you currently working on that this is blocking?)

**Comment by bluesign** [comment]
isn't this old canary?
