### ISSUE TITLE
Two problems in v0.42.0

### ISSUE THREAD

**Issue by LanfordCai** [onflow/flow-cli#723]
1. Invalid version warning:
I have upgraded to v0.42.0, but there is still a version warning ask me upgrade to v0.41.3
<img width="707" alt="image" src="https://user-images.githubusercontent.com/10380321/204684652-c5ca91d3-12d3-4aaa-9815-0d745b7114ec.png">

2. Cannot install flowser
<img width="735" alt="image" src="https://user-images.githubusercontent.com/10380321/204684807-de0d6127-0a47-40c1-932a-7a579c0c5bef.png">

**Comment by bartolomej** [comment]
Hey, @LanfordCai thanks for reporting this. Can you share some context like which OS are you using, CPU architecture,...?

**Comment by LanfordCai** [comment]
> Hey, @LanfordCai thanks for reporting this. Can you share some context like which OS are you using, CPU architecture,...?

Hi @bartolomej !

This is my system info:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/10380321/204789563-dfbe2876-0543-4bce-a0ed-50998a091128.png">

**Comment by bluesign** [comment]
hey, I have the same problem. Problem is flowser install path.

**Comment by bluesign** [comment]
workaround: `rm ~/Library/Application\ Support/flow-cli/flow-cli.settings.yaml`

**Comment by bluesign** [comment]
version isssue is about version.txt not updated.
