### ISSUE TITLE
Unable to install previous versions of Flow-CLI

### ISSUE THREAD

**Issue by ph0ph0** [onflow/flow-cli#737]
### Instructions

Running the following command:

`sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v0.41.2`

fails with the following error:

`Version v0.41.2 could not be found`

Attempting to install any previous version before v0.42.0 also fails in this way.

I have also tried installing a previous version using:

`brew install flow-cli@v0.41.2`

But this also fails:

`Warning: No available formula with the name "flow-cli@0.41.2". Did you mean flow-cli?`

### Problem

flow-cli version v0.42.0 and above are incompatible with `flow-js-testing` module. As such, all of our tests are now broken. Since we cannot roll back flow-cli to a version before v0.42.0, they will remain broken until we are unable to roll back flow-cli version. We cannot rely on the team behind `flow-js-testing` to update their module as they are incredibly slow at making updates and we have a launch in the near future.

We are currently completely blocked by this and so would really appreciate a quick resolution! Thanks :)

### Acceptance Criteria

Allow users to install versions prior to v0.42.0.

**Comment by sideninja** [comment]
@ph0ph0 can you try this to install 

`sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/50058df8aa5f999a85cfd7afae6fc2661090078a/install.sh)" -- v0.41.2`

We've switched to downloading the binaries from the release assets instead of gcp. This is a previous version of install script that should get it from there. Sorry for troubles, let me know how it is.

**Comment by ph0ph0** [comment]
Yes it works @sideninja! Thanks so much for your quick response, really appreciate your help!!!!

Should I add a PR to the developer docs for this updated command?

**Comment by sideninja** [comment]
You're welcome. 
Yeah, it might be a good note to add, this was on oversight on my side.

**Comment by sisyphusSmiling** [comment]
BTW @sideninja do you know if future versions of `flow-cli` will support `flow-js-testing`? Or is this an issue that needs to be addressed on the `flow-js-testing` side? I'm assuming this is just a temporary issue, but would like to clarify.

**Comment by sideninja** [comment]
@sisyphusSmiling I feel PMs would have a better answer for js-testing vision, but from my technical understanding some issues first needs to be addressed before it's supported by CLI.

**Comment by justinbarry** [comment]
@sideninja Is it possible to keep older versions up on homebrew somehow?

**Comment by sideninja** [comment]
@justinbarry you should be able to install them using a `brew install flow-cli@version` already.
