### ISSUE TITLE
release: update release flow to not file PRs on beta releases

### ISSUE THREAD

**Issue by chenrui333** [onflow/flow-cli#748]
generally, we dont accept beta releases on the homebrew side, can you refine the release flow to not file PRs on that? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/118509
relates to https://github.com/Homebrew/homebrew-core/pull/118510

cc @sideninja

**Comment by sideninja** [comment]
I see. Sure I will stop the pre-release. Not sure why this is not already working, it was when testing on another repo https://github.com/onflow/flow-cli/blob/master/.github/workflows/publish-release.yml#L8

**Comment by sideninja** [comment]
ohh it was probably because that release branch didn't include this yet. Will close both issues as this should be addressed going forward.
