### ISSUE TITLE
"FLOW_SIMPLEADDRESSES" flag does not work with flow.json when running emulator

### ISSUE THREAD

**Issue by ph0ph0** [onflow/flow-cli#764]
### Problem

In `flow.json`, it is possible to provide an alias for the emulator/testner/mainnet account where the contract is deployed to eg:
```
{
  ...
  "contracts": {
       "FungibleToken": {
         "source": "./cadence/contracts/FungibleToken.cdc",
         "aliases": {
           "emulator": "0x1234123412341234"
          }
        }
        "FlowToken": {
          "source": "./cadence/contracts/FlowToken.cdc",
          "aliases": {
            "emulator": "0x1234123412341234"
          }
        },
  ...
}
```

When you run the emulator with the `--simple-addresses` flag, it automatically creates accounts 0x01 to 0x04  and deploys the standard contracts across these accounts.

By running `flow accounts get <account>` on each of these accounts, you can see which contracts are deployed to each account and then update the `flow.json` with the correct emulator alias. For Fungible Token and FlowToken contracts, these are automatically deployed to 0x02 and 0x03, and so you can update the `flow.json` to this:

```
{
  ...
  "contracts": {
       "FungibleToken": {
         "source": "./cadence/contracts/FungibleToken.cdc",
         "aliases": {
           "emulator": "0x0000000000000002"
          }
        }
        "FlowToken": {
          "source": "./cadence/contracts/FlowToken.cdc",
          "aliases": {
            "emulator": "0x0000000000000003"
          }
        },
  ...
}
```

Now, when you restart the emulator with the updated `flow.json`, you get this error:

`invalid alias address for contract`

As far as I am aware, this should not cause an error?

### Steps to Reproduce

Run emulator with `contracts` key replaced by above snippet and with the `--simple-addresses` flag.

### Acceptance Criteria

Emulator can run with the simple addresses in `flow.json`.

### Context

I am currently trying to capture the `executionCost` of minting thousands of NFTs from my contract, and attempting to collect data on how the cost increases with the number of mints. This will allow me to understand the upper limits on minting via my NFT contract.

The plan was to write a script that would start the emulator with `--simple-addresses` flag, and then loop on creating accounts and purchasing an NFT from the contract. The logs are saved so the execution cost can be recovered for each tx.

The `--simple-addresses` flag was used as it makes writing the script a lot simpler - for each loop, you just increment the signer address by 1.

**Comment by sideninja** [comment]
Thank you for reporting this, it's actually coming from flowkit which is CLI core lib.

**Comment by ph0ph0** [comment]
Ok thanks very much @sideninja! 😄
