### ISSUE TITLE
Support relative path for flow json

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#778]
So when using overflow the integration tests have to be in the same folder as flow.json because flowkit does not support relative paths for loading. So if my test is in /tests and i load flow.json from ../ it has to resolve anything from that /tests folder and that does not work for other things. Is it possible to fix flowkit so that it can specify relative paths for where it expects flow.json to be?

**Comment by bjartek** [comment]
Is there any ETA for when this can be implemented?

**Comment by sideninja** [comment]
I hope I will be able to start on it in two weeks.
