### ISSUE TITLE
Filtering block response returns scientific notation for height

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-cli#779]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

When using the filter argument with `flow blocks get` and filtering for height, the returned value is formatted in scientific notation (e.g. `4.502428e+07`) instead of as an integer.

### Steps to Reproduce

Query for the latest block without a filter
```
$ flow blocks get latest -n mainnet          

Block ID                46b1ace364b3c7ac9c9467e8070c36b09a4259e9b2f3ac54af7f8c89128e387d
Parent ID               fd77e812bbe9ffb2654e2df8ec30631b9c0ff5e5f1d3609b49dc813e89df185c
Proposal Timestamp      2023-01-19 20:21:04.526768251 +0000 UTC
Proposal Timestamp Unix 1674159664
Height                  45024283
Total Seals             0
Total Collections       6
    Collection 0:       e7d54f73e7f12daacea22c869fc8217c88de7696df7a191a0ba8d4a2fb43dba2
    Collection 1:       d5f8ede9c5aa4fb6fb1635c6a583b2d185f94d54527b7f0480078300be9569bc
    Collection 2:       8c50dfb248e5d8f257ed4b7423325c3776c5ae1568bb4b62816953d0f74fa86b
    Collection 3:       43aeacd65eca25162fd81b1d464aa9fd77d835b964b12a22f8ede410212af2c4
    Collection 4:       69a9e3df80cc7a0596d03fdc3e936ef79afdcb5b663e710fa162a352fe01e7a3
    Collection 5:       d07ec309621a30b8e2434e7db8d796e8b728092700c405b69435f602f267d7ee
```

the height is listed as an `int`. In the above example: `45024283`.

Now, filter the query by `height`
```
$ flow blocks get latest -n mainnet -x height
4.502428e+07%
```

The returned value is not an integer. I assume what's happening is the return value from `filterResultValue ` here is a float:
https://github.com/onflow/flow-cli/blob/dffa320324766cb87a55cbf9db2223038cb7b0df/internal/command/result.go#L68

### Acceptance Criteria

Ideally, the implementation would include a newline after the result so the value could be copied directly from the console without the prefixed end of line character.

**Comment by sideninja** [comment]
Wow, thanks for reporting! Will fix in the next release.
