### ISSUE TITLE
Creating keys on Windows 10 produces unusable keys

### ISSUE THREAD

**Issue by milosponj** [onflow/flow-cli#78]
### Problem

While trying to create keys through the CLI they are created but the output is very weird.

### Steps to Reproduce

Using Windows 10, in Windows Powershell type `flow keys generate`

### Context

Trying to run kitty-items and this is basically the first step. Here's how the output looks in Windows Terminal:
![unknown](https://user-images.githubusercontent.com/46561585/108951882-0c9a1400-7669-11eb-83fa-df17d37a9eec.png)

**Comment by psiemens** [comment]
Thanks for reporting @milosponj!

I've confirmed the bug -- it seems to be adding an extra space to the hex string, but other than that it's a valid key. Very weird indeed 🤔 I'll investigate further

**Comment by psiemens** [comment]
My hunch is that it's something similar to this issue: https://stackoverflow.com/questions/41504786/powershell-putting-linebreaks-inappropriate-places-in-output

**Comment by sideninja** [comment]
Can't reproduce the bug with the exact setup anymore.
