### ISSUE TITLE
Deploy contracts with initializer arguments

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#79]
### Issue To Be Solved

The `flow projects deploy` command should be updated to support init arguments for contracts.

### Suggest A Solution

@sideninja actually thought about this use case while designing the new config format.

The idea is to allow for an optional advanced format in the `deployments` section. Something like this:

```json
"deployments": {
  "emulator": {
    "emulator-account": [
      "NonFungibleToken",
      {
        "name": "Kibble",
        "arguments": ["foo", "42"],
      },
      "KittyItems",
      "KittyItemsMarket"
    ]
  }
}
```

### Context

Brought up by @bjartek on the forum: https://forum.onflow.org/t/flow-cli-as-a-development-tool/809/7?u=pete

**Comment by bjartek** [comment]
Do you need type information in those arguments? Also it would be nice to reference the name of an account specified in the flow.json file there.

**Comment by bjartek** [comment]
But I think you need to be able to specify a transaction you want to use here aswell. Lets say I want to deploy a contract that takes another account as an argument and that accounts has a https://docs.onflow.org/cadence/design-patterns#capability-receiver client and connect that up.
