### ISSUE TITLE
Scaffolds should be referenced by tag

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#797]
We should add tag version of the scaffold in our scaffolds.json list so any updates to the scaffolds are reviewed.

**Comment by bluesign** [comment]
Another option is to make a public repo and get pull requests there btw

**Comment by sideninja** [comment]
I actually prefer people just making their own repos as scaffolds which can then be added here, I think it's better because you can also mark the repo as a template, and then it can also be reused on GitHub. We see how it goes we can always adapt.
