### ISSUE TITLE
Shared library for CLI command logic

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#80]
### Issue To Be Solved

With the new improvements to `flow.json` and the `flow project` command, we want to integrate this functionality into the Flow VS Code extension to provide a more seamless development environment.

To do so, we'd like to explore embedding more functionality into the Cadence language server, implemented here: https://github.com/onflow/cadence

I think it'd be great if we could accomplish this by moving shared functionality into a Go module that can be imported by the language server.

@MaxStalker @sideninja We'll go into more detail in our call later, but here are a few points to start off:
- VS Code should display accounts from `flow.json`
- VS Code should be able to execute transactions with the same address replacement functionality that is present in `flow project deploy`
- If the CLI supports loading contracts from remote locations (e.g. URL, git), then the VS Code extension should support this, too.
- The CLI and the VS Code extension should both support transaction/script arguments
- The CLI and the VS Code extension should both support multiple signers per transaction
- the list probably goes on...

**Comment by psiemens** [comment]
Hey @sideninja and @MaxStalker, I've thought about this more since our last conversation.

Currently the language server (LSP) has the following commands:

- [CommandSubmitTransaction](https://github.com/onflow/cadence/blob/d19d99342ead3831e08c1169ae60d20b5c2499bb/languageserver/integration/commands.go#L87)
- [CommandExecuteScript](https://github.com/onflow/cadence/blob/d19d99342ead3831e08c1169ae60d20b5c2499bb/languageserver/integration/commands.go#L133)
- [CommandDeployContract](https://github.com/onflow/cadence/blob/d19d99342ead3831e08c1169ae60d20b5c2499bb/languageserver/integration/commands.go#L316)
- [CommandCreateAccount](https://github.com/onflow/cadence/blob/d19d99342ead3831e08c1169ae60d20b5c2499bb/languageserver/integration/commands.go#L244)
- ~CommandCreateDefaultAccounts~
- ~CommandSwitchActiveAccount~

I don't think we need the last two commands if we move to this new structure.

As a first step towards unifying the CLI and the language server, I think we should re-implement the above functions to use the core logic from the CLI repo (this repo). The language server commands will **still call the emulator via RPC**, but they will do it using shared code from the CLI.

Before we can do this, I think we need two things:

### Language server can load `flow.json` config

I see two ways to do this:
- Language server reads `flow.json` directly from the filesystem
- Language server reads `flow.json` from the [active workspace](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders)

I think the second option is better if we can make it work. `flow.json` will already be in the set of files that the LSP is watching, and this way we can keep things consistent. The LSP can even make edits to `flow.json` using the [applyEdit](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_applyEdit) function (e.g. to add a newly created account).

### CLI command logic as modules

Currently each CLI command is implemented as a single function, and the only way to call each function is from the command line (i.e. through stdin). 

In order to implement `CommandSubmitTransaction`, for example, it should be possible for the LSP to call a [version of this function](https://github.com/onflow/flow-cli/blob/master/flow/transactions/send/send.go#L45-L67) that is callable as a function.

**Comment by MaxStalker** [comment]
So for codelens in VS Code it's gonna work like this: 
- send message to LS that file have changed
- get back codelens (if any) so editor could inject it into editor view
- (user clicks on codelens) send message to LS to execute script (currently we spawn CLI with proper args and flags here and monitor the process by extension)
- call `CommandExecuteScript` in LS
- script is being executed, we get result and send it back to editor via another message

Did I got this right?

**Comment by sideninja** [comment]
I agree with striping out the business logic. I think CLI should consist of 3 layers. 

1. API layer - this is where we parse input arguments, do validation of arguments, show errors from the arguments or interpreter, and display human-readable errors we received from the service layer.

2. Service layer - this is where we coordinate complex commands like `CommandCreateAccount` and create a function for each complex command with custom logic. This layer should return errors but not display anything on the output. This layer should handle the initialization of resources and make network requests. This layer can be stateful.

3. Model layer - this is a stateless layer where we represent data with structures. One such existing example is config (but without saving maybe).

The second and the third layer can then be extracted and used anywhere as standalone modules. These modules can also be easily tested.

CLI should talk to these modules and just handle responses and errors in a way that is clear to the user. 

I agree the mapping you stated above makes a lot of sense.

**Comment by psiemens** [comment]
> Did I got this right?
@MaxStalker Yep, that's exactly the workflow!

@sideninja I really like that breakdown 💯
