### ISSUE TITLE
New flow cli version is getting error to deploy smart contracts

### ISSUE THREAD

**Issue by Peixer** [onflow/flow-cli#821]
### Instructions

Getting error to deploy to testnet using latest version of flow cli. This is the repository used to run the tests https://github.com/Peixer/flow-playground

### Steps to Reproduce

1. Download FLOW CLI Version: v0.33.1-sc-m5, you can use this command `sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/50058df8aa5f999a85cfd7afae6fc2661090078a/install.sh)" -- v0.41.2`
2. Run `flow deploy -n=testnet --update`
3. You should get `✨ All contracts deployed successfully`
4. Download the latest FLOW CLI Version: v0.45.0, you can use this command `brew install flow-cli`
5. Run `flow deploy -n=testnet --update`
6. You should get `❌ Command Error: import from EXAMPLE could not be found: ./NonFungibleToken.cdc, make sure import path is correct`

**Comment by Peixer** [comment]
@sideninja I added this issue for future review, let me know if you need anything else from me.

**Comment by btspoony** [comment]
Same error on my project.
And it works well when falling back to v0.44.0

**Comment by sideninja** [comment]
@Peixer @btspoony will look into this now and provide an update. Related to https://github.com/onflow/flow-cli/issues/812

**Comment by sideninja** [comment]
@Peixer can you share the flow.json (without accounts keys) from the above example.

**Comment by sideninja** [comment]
I was able to reproduce what is mentioned, a fix will be available in next few hours.
