### ISSUE TITLE
Restarting the emulator changes the default flow account address and causes friction with FCL

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-cli#826]
When using `flow dev` , if we restart the emulator, the flow address set to the default account always changes. That's not a problem from the emulator perspective since we can use the shorthand import, but when using FCL, I need change the value in it's configuration to match the new one, which is annoying.

I can see two possible solutions:

> 1. Can we pin the default address so we have a deterministic value whenever the emulator restarts?
> 
> 2. Are we thinking in have a canonical import resolution for the emulator and FCL? It would be great if we can do something like we are doing for the emulator in FCL Tx's as well.
> 

> 
> ```
> # Emulator
> import "MyNFT"
> ```
> 
> ```
> # FCL
> import MyNFT from 0xMyNFT
> ```

I know I can also solve that problem by not using super commands at all, and own my `flow.json`.

That's my main issue with super commands so far, it has been hard to couple it with manual changes that I want to do in my `flow.json` file.

**Comment by sideninja** [comment]
This is being addressed as part of FCL improvement with PR WIP https://github.com/onflow/fcl-js/pull/1511
