### ISSUE TITLE
Unable to sign a transaction built previously

### ISSUE THREAD

**Issue by loic1** [onflow/flow-cli#828]
### Problem

Unable to sign a transaction previously built with `flow transactions build`: `flow transactions sign` returns an error about not being able to decode the transaction. I'm using flow-cli v0.45.1. 

### Steps to Reproduce

Build a transaction and attempt signing as in https://developers.flow.com/tools/flow-cli/complex-transactions#single-payer-and-proposer-multiple-authorizers.

### Acceptance Criteria

Should be able to sign a complex transaction;)

### Context

The same commands worked with no issues after downgrading to flow-cli v0.44.

**Comment by sideninja** [comment]
@loic1 thank you for reporting this, will provide a fix for it asap.

**Comment by sideninja** [comment]
Should be solved.

**Comment by bjartek** [comment]
Can we then close the issue?
