### ISSUE TITLE
flow transaction sign returns encoding/hex: invalid byte: U+000A

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-cli#829]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

When I try to sign a transaction built using the flow cli, I get the error ` Command Error: failed to decode partial transaction from f9486ff9486ab8996..... encoding/hex: invalid byte: U+000A`.

### Steps to Reproduce

1. Checkout this repo https://github.com/onflow/service-account/tree/vishal/test/transactions/update-contract/2023/test.
2. Build the transaction, 
`flow transactions sign ./transactions/update-contract/2023/test/test-unsigned.rlp   --config-path flow-staking.json   --signer vishal     --save ./transactions/update-contract/2023/test/sig-1.rlp`
3. Sign the transaction,
`flow transactions sign ./transactions/update-contract/2023/test/test-unsigned.rlp   --config-path flow-staking.json   --signer vishal   --filter payload   --save ./transactions/update-contract/2023/test/sig-1.rlp`

### Context

The staking contract upgrade for required for permissionless access node on Web 8th Feb will be blocked by this.

**Comment by sideninja** [comment]
Thank you for reporting this. I will try to reproduce and get back to you.

**Comment by vishalchangrani** [comment]
Acutally, I think I might have found the cause. When the rlp file is generated using the `flow build` command, it has a newline at the end. You can check this via `cat -e ./transactions/update-contract/2023/test/test-unsigned.rlp` and see that is a `$` symbol at the end.
This is what causes the error in the next step when I go to signing the transaction.
If I manually delete the new line it seems to work.
However, I am not sure why the newline gets added to the RLP in the first place :(

**Comment by sideninja** [comment]
Did you use piping to save the payload? which output format you used?
