### ISSUE TITLE
Allow `flow dev` command to look into other folder rather than "cadence"

### ISSUE THREAD

**Issue by alilloig** [onflow/flow-cli#836]
### Issue To Be Solved

Currently the new `flow dev` super command only can be run if the project is following the folder struct of cadence/contracts, cadence/transactions, etc., but in most of flow sc repos, the contracts and transactions folders are straight into the root folder.  

### Suggest A Solution

Allow using as reference the current folder where the flow dev command is being run? 
Including a `--path` flag?
Could it look for the first `flow.json` file and use that folder?

### Context

#818

**Comment by bjartek** [comment]
Yes please, at .find we have seperate backend and frontend repos and they communicte via a published versioned npm module. Our folder structure is as OP suggest.

**Comment by sideninja** [comment]
That is a good feedback, it was like that in the beginning and it changed so what we should do is have either cadence standard dirs at the top like `contracts/scripts/tranasctions` or have them inside `cadence` dir. I don't think however it's a good idea to support any, as I feel there should be some standards around folder structure we support with new projects.

**Comment by alilloig** [comment]
I agree with you @sideninja, either "complete dApp repo" folder structure or "just smart contracts repo" structure
