### ISSUE TITLE
Configuration for private accounts in environment variables

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#84]
### Issue To Be Solved

@psiemens wrote:
I think the highest priority is to give users a way to securely specify a few pieces of private data, and that can be solved easily and quickly with environment variable support. Do you think we could implement support for environment variables in this sprint, and then do flow.private.json as a follow-up feature?

I was looking at other examples and it looks like this syntax is quite common:

```
...
	"accounts": {
		"testnet-account": {
			"address": "f8d6e0586b0a20c7",
			"keys": "${env:MY_PRIVATE_KEY}"
		}
	},
...
```

A few examples:

https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables
https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-environment-variables
https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html

**Comment by bjartek** [comment]
Could we use https://github.com/a8m/envsubst here?

**Comment by sideninja** [comment]
I think that's a good idea yes. Do you want to add it or do you want me to?

**Comment by bjartek** [comment]
I can take a stab at it.
