### ISSUE TITLE
Add core contracts to default scaffold `flow.json`

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-cli#859]
### Issue To Be Solved

It is not obvious how to use core-contracts (that get deployed when the emulator starts) in the default scaffold.

### (Optional): Suggest A Solution

It would be nice if after you did `flow setup` `flow.json` would already have entries for all the core contracts.

**Comment by sideninja** [comment]
Done https://github.com/sideninja/flow-empty-scaffold/blob/main/flow.json
