### ISSUE TITLE
Emulator start fails with default flow.json

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#86]
### Steps to Reproduce

Repro: 
1) Run `flow project init`
2) Run `flow emulator start`

Observe this error in the terminal: 

```bash
flow.json contains invalid json: decode private key failed: the signature scheme UNKNOWN is not supported.
```

### Problem

The default `flow project init` should work with `flow emulator start` without having to modify the `flow.json` file.

### Context

I found a workaround that may help debug the issue:

1) Run `flow emulator start --init`
2) Copy the account object generated
3) Delete the generated `flow.json` file. 
4) Run `flow project init`
5) Replace the generated account under `"accounts": { "emulator-account": { ... }` with the object generated by `flow emulator start --init`
6) Rename "emulator-account" fields in the new `flow.json` to "service" (This is what the emulator expects?)

The emulator starts fine, but when I try `flow project deploy` I get the following error: 
```
Invalid project configuration: raw private key is not valid
```

**Comment by sideninja** [comment]
Currently project init works with project start-emulator and it is not possible to mix those commands with rest since they use the new version of config. I already refactored whole CLI to use new config and PR is open #81 which will solve this issue.
