### ISSUE TITLE
Flow dev doesnt use contracts added with Flow config

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-cli#866]
### Problem

I downloaded and added FungibleToken and FlowToken contracts via `flow config` then ran `flow dev`. I expected this to work but instead it didn't and my `flow.json` changed so that FungibleToken and FlowToken were no longer aliased.

### Steps to Reproduce

Video to reproduce this from nothing.

[![asciicast](https://asciinema.org/a/IvZxOgIc9yju6Lx3nOomlHSIj.svg)](https://asciinema.org/a/IvZxOgIc9yju6Lx3nOomlHSIj)

### Acceptance Criteria

I think this setup should probably work.

**Comment by sideninja** [comment]
Yeah noticed that yesterday, related to: https://github.com/onflow/flow-cli/issues/861
Will provide a fix in a day or so.

**Comment by sideninja** [comment]
The idea was that you no longer manually configure flow.json with flow dev. The problem is when you want to use aliases.

**Comment by sideninja** [comment]
Related to:  #870
