### ISSUE TITLE
Adding a contract doesn't add to flow.json

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#922]
When we use the `flow accounts add-contract` command we don't alter the flow.json reflecting the deployment. Which is a problem when we are doing imports as they won't get resolved due to contracts not being configured in flow.json.
This might be something we could change, but we need to think if there are any downsides.
cc @DylanTinianov

**Comment by chasefleming** [comment]
@sideninja if this functionality exists, then should there also be a ticket for remove contract?

**Comment by sideninja** [comment]
@chasefleming very good point. If we add to flow.json then we should remove as well.

**Comment by chasefleming** [comment]
@sideninja Created a ticket for it: https://github.com/onflow/flow-cli/issues/1025
