### ISSUE TITLE
Can flow cli autofix issues?

### ISSUE THREAD

**Issue by simkessy** [onflow/flow-cli#93]
I'm seeing `signature-verification-failure` issues, vscode provides a way to autofix it but i don't want to go through each file and fix it. How do I do it through the the CLI

**Comment by psiemens** [comment]
I'm not quite sure what you mean, @simkessy. Where are you seeing those errors? Do you mind providing an example?

**Comment by sideninja** [comment]
@simkessy I'm also not sure, do you mean if there is a problem with the keys format or?

**Comment by simkessy** [comment]
It's okay, I found the codemods that I need to run to fix these. Thank you.

**Comment by rachaelbrownie** [comment]
Can you share what you found? @simkessy
