### ISSUE TITLE
Keep Accounts Created in Config JSON

### ISSUE THREAD

**Issue by javiersoto15** [onflow/flow-cli#948]
### Issue To Be Solved

When creating an account through the interactive console and assigning it a name (`flow account create`), it gets saved in the flow.json. When the accounts get created manually with `flow account create --key {{key}}` it doesnt, making it impossible to start the emulator with those accounts-key pairs already created. The `flow dev` also erases any account in the flow.json if it doesnt have a contract deployed

### (Optional): Context

In cases where we may want start the emulator with the same state (ex: in a container), such as contracts and accounts created, we can not without having a external application to deploy them.
Hopefully the emulator would initialize creating the accounts that are in the flow.json already

**Comment by chasefleming** [comment]
Breaking this into two tickets: https://github.com/onflow/flow-cli/issues/966
