### ISSUE TITLE
Maintain Account Key in fresh Flow Dev Runs

### ISSUE THREAD

**Issue by javiersoto15** [onflow/flow-cli#949]
### Issue To Be Solved

The objective is for the account objects that are in the flow.json file to maintain the key specified there when running the `flow dev` command to set up the project in a fresh emulator run.

Currently when we want to deploy a contract with the specified account in the flow.json through the flow dev command, a new key is generated and replaces the existing. It causes incompatibility with programs that use that key alongside the emulator within the development cycle as it always changes.

### (Optional): Suggest A Solution

Not a technical solution, but hopefully there is a way to maintain those keys similar to what we can do to the service account key if we specify it.

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

### (Optional): Context

When simulating a wallet and the contracts deployed by it, there is no control over the key that's used to deploy it, even though the account address does remain the same. It makes it hard to use `flow dev` and any outside program to interact with them

**Comment by chasefleming** [comment]
@javiersoto15 the PR to use the service account key for generation has been released. Is this issue resolved for you now?
