### ISSUE TITLE
Execute scripts panics if you send in nil to the utils.ScriptQuery pointer var

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-cli#952]
### Instructions

run ExecuteScript with nil as query field that is a pointer

### Problem

`    --- FAIL: TestScriptIntegrationNew/Get_length_from_pointer_map (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1030584d8]

goroutine 3787 [running]:
testing.tRunner.func1.2({0x1037099e0, 0x10454cdb0})
    /opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
    /opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1399 +0x378
panic({0x1037099e0, 0x10454cdb0})
    /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x204
github.com/onflow/flow-cli/pkg/flowkit/gateway.(EmulatorGateway).ExecuteScript(0x14000a63d00, {0x14000236690, 0x61, 0x70}, {0x1045b5228?, 0x12d126350?, 0x104bf45b8?}, 0x0)
    /Users/bjartek/go/pkg/mod/github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20230331185616-341a9bfb3532/gateway/emulator.go:183 +0x58
github.com/onflow/flow-cli/pkg/flowkit/services.(Scripts).Execute(0x14001409050, 0x140012938c0, {0x1031d8782, 0x8}, 0x2?)
    /Users/bjartek/go/pkg/mod/github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20230331185616-341a9bfb3532/services/scripts.go:88 +0x150`
### Steps to Reproduce

<share any logs/screenshots or steps to replicate>

### Acceptance Criteria

An empty pointer variable should result in running on latest block

### Context

overflow

**Comment by bluesign** [comment]
I think it should not be pointer there ( passing struct is better option )

**Comment by sideninja** [comment]
This will be fixed as part of flowkit refactor.
