### ISSUE TITLE
Unify contract name detection

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#976]
There are a couple of places where we still ask the user to provide the contract name as well as the contract source. We should get the contract name from the source and not ask the user to provide it, due to possible typos, additional inputs etc.

One such place is the add contract command: `flow config add contract`.

**Comment by chasefleming** [comment]
@sideninja is this meant to be closed? Was it completed somehow? Don't see an issue associated

**Comment by sideninja** [comment]
Yes, it was completed. Not sure why PR wasn't linked.
