### ISSUE TITLE
Flow dev does not remove contracts after deletion

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#979]
### Problem

In "flow dev," if you create a contract and then remove it, the contract name and path stays in the "contracts" section of flow.json

**Comment by sideninja** [comment]
It looks like a regression on persisting flow.json. When the contract is deleted that's detected in the dev command but it looks like not saved in flow.json. Thank you for finding this. Also on this topic, I feel after the contract is deleted it should be removed from the Flow network. I created another issue fo it: https://github.com/onflow/flow-cli/issues/981
