### ISSUE TITLE
Enable Attachments

### ISSUE THREAD

**Issue by C-3PFLO** [onflow/flow-cli#982]
### Issue To Be Solved

Attachments are now available on Testnet but not yet enabled for flow emulator.

```
> flow version
Version: v0.49.0
```
but tests still throw
```
error: attachments are not enabled and cannot be used in this environment
```

**Comment by sideninja** [comment]
Thank you for reporting, we will update the emulator verison.

**Comment by turbolent** [comment]
Depends on https://github.com/onflow/flow-emulator/pull/360

**Comment by turbolent** [comment]
Released in https://github.com/onflow/flow-emulator/releases/tag/v0.47.0
