### ISSUE TITLE
Execute FLIX transactions/scripts 

### ISSUE THREAD

**Issue by nvdtf** [onflow/flow-cli#984]
We like to be able to run FLIX interactions from the Flow CLI directly. 

### Approach

Let's consider the normal transaction send flow:

```
flow transactions send <path> ...
```

We can extend `<path>` into:
* Can be a filesystem `path`:
  * If a Cadence file is passed, the current behaviour is expected.
  * If a FLIX interaction is passed locally, Flow CLI will parse and run it.
* Can be a `URL`: 
  * If a Cadence file is fetched, Flow CLI will run it.
  * If a FLIX interaction is fetched, Flow CLI will parse and run it.
* Can be `flix:<name>`:
  * The Flow FLIX server is checked for named interactions with the passed `<name>`

If a FLIX interaction is passed, Flow CLI will first show a Yes/No confirmation screen with interaction template's:
* Title
* Description
* Audits

### References
https://github.com/onflow/flips/blob/main/flips/20220503-interaction-templates.md
https://github.com/bjartek/overflow/blob/flix2/flix.go

**Comment by sideninja** [comment]
I think this is a good idea of how to approach this.

**Comment by bjartek** [comment]
I have some code in overflow that does this

**Comment by nvdtf** [comment]
@bjartek, we're planning to extract it into a new library so we can reuse it in CLI, Go SDK and even overflow.

**Comment by bjartek** [comment]
cool, then we should talk. That code has some required parts in overflow that should also move, the branch is called flix2 btw, and i even belive there is a flix3 that has a first attempt at solving the new. 1.1 spec of flix.

**Comment by bjartek** [comment]
ahh i see it was reference in the issue already. sorry for making noise.

**Comment by JeffreyDoyle** [comment]
It would be nice if we could execute scripts/transactions by ID as well: 

eg: `flow scripts execute flix:290b6b6222b2a77b16db896a80ddf29ebd1fa3038c9e6625a933fa213fce51fa`

**Comment by JeffreyDoyle** [comment]
Might be a good idea to namespace names and id's as well:

eg: `flow scripts execute flix:id:290b6b6222b2a77b16db896a80ddf29ebd1fa3038c9e6625a933fa213fce51fa`
eg: `flow scripts execute flix:name:transfer-tokens`
